### ISSUE TITLE
Slice bounds out of range exception

### ISSUE THREAD

**Issue by rbuchmann-fdc** [dgrijalva/jwt-go#100]
Hi, 
I installed the jwt tool with go get github.com/dgrijalva/jwt-go/cmd/jwt and ran it using your example:

```bash
echo '{"foo":"bar"}' | jwt -key mykey -alg RS256 -sign - | jwt -key mykey.pub -verify -
```

It crashed with a "slice bounds out of range" Error in
main.verifyToken.func1 -> app.go:123
github.com/dgrijalva/jwt-go.Parse -> jwt-go/jwt.go:127
main.verifyToken -> jwt/app.go:127
main.start -> jwt/app.go:57 +0x67
main.main -> jwt/app.go:46

Hope that helps.

**Comment by anfernee** [comment]
I have the same issue on master. On release_3_0_0 it's 

Error: Error signing token: key is invalid or of invalid type

**Comment by dgrijalva** [comment]
Yup.  That definitely happens.  Let me have a look...
