### ISSUE TITLE
Adding compression for the claims

### ISSUE THREAD

**Issue by szank** [dgrijalva/jwt-go#101]
Hi, in our project the claims part of the JWT token is getting really long. I was wondering if it would be possible to compress the data in the claims part. 
It would look pretty straightforward, 
I would add an 'compression' : 'gzip' key and value to the header map. This can be done by adding a new argument  to the jwt.New() function. 
The rest would be transparent. Just add compression between JSON encoding and Base64 encoding, 
and decompression symmetrically. 

I would rather contribute to the main repo instead of forking it or doing the same thing in our code.

**Comment by dgrijalva** [comment]
It's a cool idea.  Is this supported by the spec?

**Comment by szank** [comment]
There is no mention of claims compression in the RFC. I did have only a cursory glance, but it looks like it is not forbidden. I think this should be still ok, as the implementation i was thinking about would fallback gracefully in case of any problems. 

I am using the same approach to compression function as to the one used for signing methods. 
If there is not 'compression' entry in the JWT header it would fall back to no op compression alg.

**Comment by szank** [comment]
Hi, just pinging to check if there are any updates on this.

**Comment by bbrks** [comment]
#102

**Comment by dgrijalva** [comment]
See #102
