### ISSUE TITLE
Should exp and nbf really be float64 or int64?

### ISSUE THREAD

**Issue by someone1** [dgrijalva/jwt-go#103]
The example given in the [readme](https://github.com/dgrijalva/jwt-go/blob/master/README.md) shows something like:

```go
token.Claims["exp"] = time.Now().Add(time.Hour * 72).Unix()
```

And this makes sense, feels like idiomatic Go. However, the [actual implementation](https://github.com/dgrijalva/jwt-go/blob/master/parser.go#L87) that checks for expired tokens expects a `float64`. What is the proper methodology here? I'm guessing `float64` as the tests were written this way, so then maybe the README.md needs to be updated accordingly?

I'd be interested in thoughts on this!

**Comment by dgrijalva** [comment]
It's a side effect. The json parser, by default, returns all numbers as float64.

-dave

**Comment by treeder** [comment]
What's the best way to deal with this?  Might be a good idea to pass in a struct pointer to Parse() so it can unmarshal it properly.

**Comment by dgrijalva** [comment]
The 3.0 branch allows that. Alternatively, you can create an instance of Parser and set the JSON number flag.

-dave

**Comment by dakom** [comment]
Yes but the parser currently limits the values to float64 for checking. While it's unlikely someone will set values beyond that, I submitted a pull request to fix: https://github.com/dgrijalva/jwt-go/pull/121

**Comment by dgrijalva** [comment]
@treeder if you'd like a workaround for today, use `Parser`.  The main `Parse` function is just a wrapper around this.  You can override some options, including using the `json.Number` instead of `float64`.

**Comment by treeder** [comment]
Ok, thanks @dgrijalva

**Comment by dgrijalva** [comment]
`master` and `release_3_0_0` both now correctly handle `json.Number`.  If you want that behavior, create a `jwt.Parser` and set the `UseJSONNumber` flag before parsing your token.

I'll make a new release from master today.  3.0.0 is getting close.
