### ISSUE TITLE
Any example of Parsing when using keys?

### ISSUE THREAD

**Issue by polds** [dgrijalva/jwt-go#104]
All of the examples I've found are for validating a token using `HS256` using a `[]byte()` for the secret. I'm wondering if there are any examples for validation when using keys?

**Comment by elithrar** [comment]
A `[]byte` is the de-facto standard for providing a key across most of the `crypto/*` packages outside of the `crypto/rsa` package. Usually this means you pull the key (as a string) from your environment (i.e. `os.Getenv`) and then wrap it - `[]byte(someKey)`.

If that's not what you meant, then let me know.

**Comment by polds** [comment]
Ah.. So the following would still work using a private key:

```
token, err := jwt.Parse(myToken, func(token *jwt.Token) (interface{}, error) {
		return []byte(rsaKey), nil
	})
```

**Comment by dgrijalva** [comment]
Be careful here.  `HS256` is not designed to use an actual key.  The `HS` class of signing methods uses symmetric key encryption, and the secret can be any random bytes.

If what you really mean to use is `RS256`, you _really_ don't want to pass those keys in for `HS256` verification.  See the following link for details on what can go wrong: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by dgrijalva** [comment]
@polds your example will work fine if `rsaKey` is a string containing the bytes of the shared secret.

**Comment by elithrar** [comment]
To pick nits: HS256 is HMAC-SHA-256, a keyed hash, not encryption. The
HS256 algorithm as used here just signs the token contents, and allows you
to verify that by re-signing on a request and comparing. Nothing is
actually encrypted—if you're not using HTTPS, an cafe WiFi snooper could
read the contents.

Sidebar: it's my opinion that HS256 should be the go-to algorithm for
nearly all JWT users, as you shouldn't be storing sensitive data inside
your JWT.

HTTPS (TLS) takes care of the transport security, and it's extremely rare
that clients need to verify the JWT with an RSA public key. Avoid the
complexity unless you are sure you need it.

**Comment by dgrijalva** [comment]
I think that misses the point a bit.  `RS256`, which is cryptographic signing, also does not encrypt the contents.  The main reason to use `RS` over `HS` has to do with who's going to be verifying the tokens.  `RS` tokens can be verified without having the key used to create tokens.

**Comment by dgrijalva** [comment]
There is a companion spec, `JWE`, which supports encrypted fields.  `JWT` only addresses signing.

**Comment by polds** [comment]
Thanks for the tips both. Most helpful.
