### ISSUE TITLE
Missing checks on jwt.io

### ISSUE THREAD

**Issue by localhosted** [dgrijalva/jwt-go#105]
According to jwt.io, jwt-go is missing the following checks:

*iss check
*sub check
*aud check
*iat check
*jti check

I am not sure what exactly they entail, but does their lack create any security concerns?

**Comment by dgrijalva** [comment]
Their use can be somewhat application specific.  If you are producing and consuming your own tokens, you should be aware which of these fields needs additional validation.  If you are consuming tokens produced elsewhere, see the provider's documentation.

This library is intentionally sparse to reduce overhead and avoid getting in the way of its users.  The focus is on parsing of tokens an validation of signatures.  There are a few built in claims verifiers where the behavior is consistently defined (such as `exp`), mostly for convenience.

If you're concerned by this, have a look at the 3.0.0 milestone.  The claims verification stuff is more explicit about what it does and provides opportunities for developers to override and extend.

**Comment by localhosted** [comment]
Ok, thanks.
