### ISSUE TITLE
Keep getting errors when parsing

### ISSUE THREAD

**Issue by Snorlock** [dgrijalva/jwt-go#106]
I use this method in creating token:

    token := jwt.New(jwt.SigningMethodHS256)
    token.Claims["id"] = user.UserID
    token.Claims["iat"] = time.Now().Unix()
    token.Claims["exp"] = time.Now().Add(time.Second * 3600 * 24).Unix()
    jwtString, err := token.SignedString([]byte("mysupersecretkey"))
    fmt.Println(jwtString);

Then I take that string i get echoed out an try to do a simple call to the my root route which has this inside it:

``` golang
func IndexHandler(env *db.Env, w http.ResponseWriter, r *http.Request) error {
  jwtString := r.Header.Get("Authorization")
  token, err := jwt.ParseFromRequest(jwtString, keyFn)
  fmt.Println(token)
  fmt.Println(err)
  if err == nil && token.Valid {
      // token parsed, exp/nbf checks out, signature verified, Valid is true
      fmt.Fprint(w, "Welcome!\n")
      return nil;
  }

  fmt.Println("index");
  fmt.Fprint(w, "NOT AUTHORIZED")
  return nil
}

func keyFn(token *jwt.Token) (interface{}, error) {
    return []byte("mysupersecretkey"), nil
}
```

But I keep getting error illegal base64 data at input byte 6 or illegal base64 data at input byte 4.

What am i missing? I have read that i need to return an interface from the keyFn, ref this http://stackoverflow.com/questions/25848215/go-and-parsing-token-with-jwt-go.

But I dont understand what that should be? Any help here? Cant seem to find any examples that work for me. Also tried this example, https://sendgrid.com/blog/tokens-tokens-intro-json-web-tokens-jwt-go/, but its pretty the same thing.

**Comment by dgrijalva** [comment]
ParseFromRequest expects a request. The trouble your running into is, the header value will likely be 'bearer <your token>'. 

-dave

**Comment by Snorlock** [comment]
Sorry I did a copy paste and undo error. I tried both parseFromRequets and parse. This was suppose to be parse and jwtString, and I also tried parseFromRequest and the request that comes from the method.

Is it suppose to be "bearer <my-token>" or "Bearer: <my-token>"?

**Comment by Snorlock** [comment]
It seems like my problem was that i did Authorization with Bearer: my-token. That is not legal I quess. But it was a very obscure error. That big B and : broke the code. Worked with just bearer my-token.

Then the string version worked aswell, having that secretstring as a byte string.

**Comment by Snorlock** [comment]
I read somewhere that the bearer should be written Bearer: \<my-token>, but this would have been solved with a bit better error handling. Feks returnin error if authorization bearer is not written bearer \<my-token>

**Comment by Snorlock** [comment]
Added a pullrequest for other noobs like me: https://github.com/dgrijalva/jwt-go/pull/107

**Comment by dgrijalva** [comment]
#107 has landed.  Should we close this now?

**Comment by Snorlock** [comment]
Sounds good!
