### ISSUE TITLE
ValidationError struct needs a exported field of type error

### ISSUE THREAD

**Issue by emanoelxavier** [dgrijalva/jwt-go#108]
Currently there is no way for callers of the func Parse to handle error types returned by the extension point KeyFunc. In other words, in my implementation of KeyFunc I return my own error type with my error code in it. Parse does not surface this information to its caller and therefore I cannot easily handle my own error type and code. My suggestion to tackle this is to include an exported field on the type ValidationError, something like "InnerError error", here you can place the whole error returned by KeyFunc. Currently when KeyFunc fails I see that you place the .Error() of that failure in the ValidationError.err but this is not quite the same as keeping the whole KeyFunc error type since that can contain more information. Another option is to provide another extension point so that KeyFunc errors can be handled on a custom fashion.

**Comment by dgrijalva** [comment]
This is a good idea. I'd be happy to review a PR, or I can put it on the list for 3.0

**Comment by dgrijalva** [comment]
This issue replaced by #112
