### ISSUE TITLE
Security issue when token is expired or not yet valid

### ISSUE THREAD

**Issue by mikegleasonjr** [dgrijalva/jwt-go#114]
The parser returns an error when the token is expired **before** verifying it with the signing key.

So one could forge an expired token with some claims and a careless client app could be compromised.

If the token is expired, I still want to know if it is signed by me and I can trust the claims.

I use expired tokens when re-issuing access tokens with refresh tokens. Instead of just providing a refresh token, I also pass the old access token and I check if the claims matches my database entries for the refresh token. Everything is there in the token (subject, audience, etc) I don't want to pass those as parameters to my API. Also, those could be forged.

We just have to move the `// Check expiration times` block below the `// Perform validation` block in `parser.go`. Do you want me to do a PR?

**EDIT:** same security issue could happen with the `nbf` claim, when the token is not yet valid.

**Comment by dgrijalva** [comment]
It would probably makes sense to return _all_ errors when a token is invalid for multiple reasons.  I'm not super keen on the idea of relying on expired tokens, but there's no reason the library should get in your way if that's what you want to do.

**Comment by mikegleasonjr** [comment]
I'm not saying returning a valid token if it is expired, we still should return the error.

But when I get `ValidationErrorExpired` with a **forged** token, it is not expired. This is an invalid token and the function should return `ValidationErrorSignatureInvalid`.

**Comment by mikegleasonjr** [comment]
Also, the specs says about the "exp" claim: [...] Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew."

If "there's no reason the library should get in your way if that's what you want to do", means re-writing the parse function client-side, then why am I using a library? ;)

**Comment by dgrijalva** [comment]
I think running the signature validation first is probably fine, maybe even better.

The Errors property is a bitfield.  We could just change it so it always runs all validations and returns the complete set of errors.  That way, you can decide which ones you care about.

**Comment by mikegleasonjr** [comment]
That would be awesome!

**Comment by dgrijalva** [comment]
Looks like this is already how it works:

```go
	// Check expiration times
	vErr := &ValidationError{}
	now := TimeFunc().Unix()
	if exp, ok := token.Claims["exp"].(float64); ok {
		if now > int64(exp) {
			vErr.err = "token is expired"
			vErr.Errors |= ValidationErrorExpired
		}
	}
	if nbf, ok := token.Claims["nbf"].(float64); ok {
		if now < int64(nbf) {
			vErr.err = "token is not valid yet"
			vErr.Errors |= ValidationErrorNotValidYet
		}
	}

	// Perform validation
	token.Signature = parts[2]
	if err = token.Method.Verify(strings.Join(parts[0:2], "."), token.Signature, key); err != nil {
		vErr.err = err.Error()
		vErr.Errors |= ValidationErrorSignatureInvalid
	}
```

**Comment by mikegleasonjr** [comment]
Oh man I looked at every return path before and they were always returning when catching an error.

My bad sorry for the confusion!

**Comment by dgrijalva** [comment]
The earlier errors return early because they cannot proceed.  They are for things like invalid JSON.
