### ISSUE TITLE
better error message

### ISSUE THREAD

**Issue by james-lawrence** [dgrijalva/jwt-go#115]
"token is invalid" is pretty much useless for determining the cause. I suggest updating the Error() from:
```
func (e ValidationError) Error() string {
	if e.err == "" {
		return "token is invalid"
	}
	return e.err
}
```
to something along the lines of
```
func (e ValidationError) Error() string {
	if e.err == "" {
		isError := func(errors, t uint32) bool {
			return errors&t == t
		}
		problems := []string{"token is invalid"}
		if isError(e.Errors, ValidationErrorExpired) {
			problems = append(problems, "expired")
		}

		if isError(e.Errors, ValidationErrorMalformed) {
			problems = append(problems, "malformed")
		}

		if isError(e.Errors, ValidationErrorNotValidYet) {
			problems = append(problems, "not valid yet")
		}

		if isError(e.Errors, ValidationErrorSignatureInvalid) {
			problems = append(problems, "signature invalid")
		}

		if isError(e.Errors, ValidationErrorUnverifiable) {
			problems = append(problems, "unverifiable")
		}

		return strings.Join(problems, ", ")
	}
	return e.err
}
```

**Comment by dgrijalva** [comment]
I'm not opposed to it, however, pretty much everywhere an error is generated populates that field.  I don't know that there are any situations where the bitfield is populated but not the string.  That code probably never runs; it's a catch-all.

**Comment by derekdowling** [comment]
I definitely would benefit from this as well. I have this same error and have been putting off tracking it down because it's so open ended. This is despite having pieced together as many examples as possible to try and make sense of how to implement this.

**Comment by dgrijalva** [comment]
Do you feel this would be satisfied by #112 ?

**Comment by dgrijalva** [comment]
This should actually be covered by work already done in 3.0.0.  (in addition to #112 )
