### ISSUE TITLE
No token returned from jtw.ParseFromRequest

### ISSUE THREAD

**Issue by tanepiper** [dgrijalva/jwt-go#118]
Hi there, I've recently just started with Go today so excuse the code and I'm aware this is not a fine example :)

I'm trying to implement a middleware in Gin that checks all requests for a valid token.  So far I have:

```
package auth

import (
        "github.com/gin-gonic/gin"
        "github.com/dgrijalva/jwt-go"
        "errors"
        "regexp"
        "net/http"
)

func CheckJWTToken () gin.HandlerFunc {
        return func (context *gin.Context) {
                defer func() {
                        // FIXME: Probably the worst way to check this
                        notAuthUrl, err := regexp.MatchString("/auth/", context.Request.RequestURI)
                        notPublicUrl, err := regexp.MatchString("/public/", context.Request.RequestURI)
                        
                        if err != nil {
                                context.Err()
                        }

                        if !notAuthUrl && !notPublicUrl{

                                token, err := jwt.ParseFromRequest(context.Request, func(token *jwt.Token) (interface{}, error) {
                                        return []byte("jkklfjafjlfdjkafjsladg;wehg;lwejf;wekjf;weklfjlekfjlfjaslk;fl"), nil
                                })
                                
                                if err != nil {
                                        context.Error(errors.New("There has been an issue parsing the token"))
                                }

                                if !token.Valid {
                                        context.Status(http.StatusForbidden)
                                }
                        }
                }()

                context.Next()
        }
}
```

However `token` is `<nil>` if I `fmt.Print` it, although in my debugger is is showing as an instance of `github.com/dgrijalva/jtw-go.Token`  I've checked the Gin context.Request and it is an instance of a http.Request, and I'm passing `Authorization: Bearer <token>` in as the header on each request, and also some requests without it, when it's there it is in the `context.Request.Header` map.

Any ideas?

**Comment by tanepiper** [comment]
Ahh never mind, resolved it.  It was passing in an non-valid token (from earlier tests where I was just passing `foobar` in as the token). But I suppose this could be a bug? It produced no `err` for me to handle and just make token `nil` so `token.Valid` was not available to check.

**Comment by metal3d** [comment]
I agree with @tanepiper - an invalid Authorization header (forgotten "Bearer") create a panic "runtime error: invalid memory address or nil pointer dereference". IMHO the method should set "token.Valid" to false.

**Comment by metal3d** [comment]
Houps... forget... I didn't check the returned error from method. It's ok, "error" contains "no token present in request" as expected.

**Comment by tanepiper** [comment]
@metal3d Yep can probably close this one, I realised what I'd done - basically coming from node, I had this:

```
token, err := jwt.ParseFromRequest(context.Request, func(token *jwt.Token) (interface{}, error) {
				return signingToken, nil
			})

			if err != nil {
				context.AbortWithStatus(http.StatusForbidden)
			}

			if token == nil {
				context.AbortWithStatus(http.StatusForbidden)
			}

			if token != nil && !token.Valid {
				context.AbortWithStatus(http.StatusForbidden)
			}
```

Of course these if statements don't return so it was dropping through to the next one, simple fix with:

```
token, err := jwt.ParseFromRequest(context.Request, func(token *jwt.Token) (interface{}, error) {
				return signingToken, nil
			})

			if err != nil || token == nil || token != nil && !token.Valid {
				context.String(http.StatusForbidden, "You are not authorised to access this")
			}
```

I can do better error checking with this, but for now I'm happy that this resolves my issue.
