### ISSUE TITLE
The example code to validate the alg doesn't work

### ISSUE THREAD

**Issue by thinkhy** [dgrijalva/jwt-go#123]
The example code to validate the alg doesn't work, I changed the code to compare string of Alg name instead of verifying type name, it then works well in my project.

```
    token, err := jwt.Parse(jwtString, func(token *jwt.Token) (interface{}, error) {
         // Don't forget to validate the alg is what we expect
         // if _, ok := token.Method.(*jwt.SigningMethodRSA); !ok {
         if token.Method.Alg() != "HS256" {
             return key, errors.New("Unexpected signing method")
         }
    ... ...
```

**Comment by dgrijalva** [comment]
Either version should work.  Try comparing against `*jwt.SigningMethodHSA` if you're using an `HS256` token.

**Comment by thinkhy** [comment]
Still doesn't work ...  This time I hit compile error:

      ./login.go:143: undefined: jwt.SigningMethodHSA

Seems there is no type named as "SigningMethodHSA":

      ➜  src grep -R -i SigningMethodHSA   github.com/dgrijalva
      ➜  src echo $?
      1

**Comment by dgrijalva** [comment]
Sorry.  I typed that from my phone.  The correct type is `SigningMethodHMAC`.  This one matches `HS256` and friends.

The one in the example code will match the `RS256` family.

**Comment by thinkhy** [comment]
SigningMethodHMAC is the correct type I'm looking for:)  Problem resolved.

Thanks
