### ISSUE TITLE
Changes to token within keyFunc ignored by parse

### ISSUE THREAD

**Issue by cameront** [dgrijalva/jwt-go#127]
I'd like to be able to parse claims from a signed token when I'm sure that the token is valid (but don't have access to the signing key). E.g.:
```
func unverifiedParse() jwt.Keyfunc {
	return func(token *jwt.Token) (interface{}, error) {
		token.Method = jwt.SigningMethodNone
		token.Signature = ""
		return jwt.UnsafeAllowNoneSignatureType, nil
	}
}
```

However, modifications like this to the token object don't work as expected, because the "parts" are cached by Parse and used in the verification, ignoring my changes: 
https://github.com/dgrijalva/jwt-go/blob/master/parser.go#L104

Would you accept a PR that moved the setting of token.Signature to before keyfunc was applied?

**Comment by dgrijalva** [comment]
You could just parse the token and ignore the error, no?

```
if token, _ := jwt.Parse(myTokenString, nil); token != nil {
   // Do something with parsed, but unverified token
}
```

Do you control the signing environment?  You may get benefit from using an asymmetric signing method such as `RS256`.  It would allow you to parse and verify the token without having the signing key (just the public key).

**Comment by cameront** [comment]
I don't want to ignore the error because I am interested in payload validity - e.g. exp and nbf concerns. My use case is caching valid tokens in a microservice environment to prevent load on the auth service. The auth service generates/verifies tokens. Other services verify tokens (with the auth service) they've never seen before, but cache verified token strings for some period of time. If the token is cached, I'd love to ignore the signature but parse/validate the payload, which I was hoping to to by making it looked like an unsigned token while parsing.

I could ignore the error and manually check exp and nbf I suppose, or use RS256 and share the public key, but both are more work than I'd prefer to do. :) Or maybe I'll just cache the claims returned by the auth service rather than just a "valid" flag. 

Feel free to close if this doesn't sound like a use-case you want to support.

**Comment by dgrijalva** [comment]
I can't think of any reason we shouldn't populate the signature field before calling `keyFunc`.  

An alternative approach that may be a bit more explicit would be to implement your own signing method.  It requires less manipulation of the token.

```go
type IgnoreSignature struct {}

func (s *IgnoreSignature) Alg()string{
  return "ignored"
}

func (s *IgnoreSignature) Verify(signingString, signature string, key interface{}) error{
  return nil
}

func (s *IgnoreSignature) Sign(signingString string, key interface{}) (string, error) {
  return "", nil
}

func unverifiedParseKeyFunc(token *jwt.Token) (interface{}, error) {
    token.Method = &IgnoreSignature{}
    return "", nil
}
```

**Comment by cameront** [comment]
Oh good idea, I like this approach better than coercing into None.
