### ISSUE TITLE
Delay (un-)marshal using e.g. json.RawMessage

### ISSUE THREAD

**Issue by arekkas** [dgrijalva/jwt-go#134]
Currently, (un)-marshalling of headers and claims is done in the library. The result is `map[string]interface{}`. As it is known, `interface{}` require type assertions and are generally nasty to handle.

IMHO it should be possible to use something like `json.RawMessage` instead, giving the developer the freedom to choose a data structure that makes sense for his use case.

**Comment by dgrijalva** [comment]
Some of the data, especially that in the head section, is required for correctly parsing and verifying a token.  We have been, however, working on some changes that allow custom parsing of claims while still giving the library access to the necessary fields for it to be useful.  Have a look at the 3.0 branch, which is nearing release:  https://github.com/dgrijalva/jwt-go/tree/release_3_0_0

**Comment by arekkas** [comment]
Oh ok cool, that looks pretty neat. I had a big post scheduled with a use case for json.RawMessage but while writing that I realised that, like you said, there are some things which have to be predefined and where it don't make sense to abstract those away. I'll give v3 a shot! Thanks for the quick reply
