### ISSUE TITLE
ParseRSAPublicKeyFromPEM returns wrong error ErrNotRSAPrivateKey (copy+paste issue?)

### ISSUE THREAD

**Issue by jonathaningram** [dgrijalva/jwt-go#135]
See https://github.com/dgrijalva/jwt-go/blob/master/rsa_utils.go#L64

It is:

```go
return nil, ErrNotRSAPrivateKey
```

Should it be another new error type `ErrNotRSAPublicKey`?

**Comment by dgrijalva** [comment]
Yep.  That's definitely a bug.  Thanks for reporting.
