### ISSUE TITLE
How do you retrieve fields from Claims?

### ISSUE THREAD

**Issue by seanlindo** [dgrijalva/jwt-go#142]
I'm utilizing a middleware library that is performing the following operation:

`parsedToken, err := jwt.Parse(token, m.Options.ValidationKeyGetter)`

This is placed in the request's context and I'm attempting to access it in the handler:

`u := context.Get(r, "user")`
`c := u.(*jwt.Token).Claims`

There are several examples on the internet of interacting with `Claims` like you would a map, but this only returns errors. I've tried accessing fields in `Claims` like you would a map, but I only get errors because `jwt.Claims` does not support indexing. 

Logging this object uncovers the following:

`INFO[0001] map[iss:https://redacted.com sub:1234 aud:web exp:1.466211685e+09 iat:1.466175685e+09]`

How do I actually use this object?

**Comment by dgrijalva** [comment]
The type of `Claims` has changed in the latest release.  It used to be a simple map, now it's an interface type.  Have a look at MIGRATION_GUIDE.md for more details.

The simple answer is, based on your usage, you just need to cast it:
`c := u.(*jwt.Token).Claims.(jwt.MapClaims)`

**Comment by seanlindo** [comment]
Hi there, 

After reading through the source code, I came to the same conclusion; however, I needed to lift some code from MapClaims to parse the particular field:

`aud, _ := foo["sub"].(string)`

Is this the best way moving forward? I'm using auth0 as my provider, so I suspect simply forking their repository and providing `StandardClaims` as the claims object instead of letting `MapClaims` be provided as the default. would be more straightforward.

**Comment by dgrijalva** [comment]
`MapClaims` is just an alias to `map[string]interface{}` that conforms to `Claims`.

If you know ahead of time all the fields you're going to care about, I'd suggest switching to use a custom claims format.  You can use `StandardClaims` by itself, or embed it in your own type.  Based on the example output above, it doesn't look like you have any custom properties, so `StandardClaims` should treat you fine.

`parsedToken, err := jwt.ParseWithClaims(token, &StandardClaims{}, m.Options.ValidationKeyGetter)`

**Comment by dgrijalva** [comment]
If you do want to add other fields, you can:

```
type MyClaimsType struct {
  *StandardClaims
  MyKey string `json:"my_key"`
}
```

**Comment by seanlindo** [comment]
I would think [this library](https://github.com/auth0/go-jwt-middleware) would be best served by some updated documentation and an option to pass in your own claim object; however, that's well out of scope here. 

Thanks a ton!

**Comment by dgrijalva** [comment]
I don't know what the purpose of that library is for.  New features in 3.0 may obviate the need for this:

* You can supply a list of valid signing methods to the parser: see `parser.go`
* The new `request` subpackage contains all you'll likely need for extracting tokens from requests

**Comment by seanlindo** [comment]
It's JWT middleware. After checking out the Request sub-package and reading the Migration notes (I must have missed those before, they're very helpful) it makes sense to create our own middleware package for my organization.

**Comment by dgrijalva** [comment]
I believe that. Let me know if I can be helpful.

-dave
