### ISSUE TITLE
invalid operation: token.Claims["ID"] (type jwt.Claims does not support indexing)

### ISSUE THREAD

**Issue by LeBronoMars** [dgrijalva/jwt-go#143]
This is working fine in my localhost, but when i'm trying it in aws ec2..i cant build and i'm getting the ff. error
![screen shot 2016-06-18 at 10 26 39 am](https://cloud.githubusercontent.com/assets/17944694/16168588/3091b34c-353f-11e6-8c5f-181cb99b7851.png)

and here is my code
![screen shot 2016-06-18 at 10 21 46 am](https://cloud.githubusercontent.com/assets/17944694/16168576/8e0f3202-353e-11e6-91a6-5149fa78c484.png)

**Comment by LeBronoMars** [comment]
Ohh ok..sorry.. there's an update..gonna close this one

**Comment by kwk** [comment]
I have the same issue and I'd like to know which update you were talking about @LeBronoMars

**Comment by dgrijalva** [comment]
@kwk this library was updated at the end of last week.  The API for Claims has changed.  See https://github.com/dgrijalva/jwt-go/blob/master/MIGRATION_GUIDE.md for details.  Or you can continue to use 2.x.

**Comment by Hokutosei** [comment]
@dgrijalva I'm having the same problem, I wonder how did everyone solved this problem?

here is my code

```
	token := jwt.New(jwt.SigningMethodRS512)
	token.Claims["exp"] = time.Now().Add(time.Hour * time.Duration(settings.Get().JWTExpirationDelta)).Unix()
	token.Claims["iat"] = time.Now().Unix()
```

**Comment by dgrijalva** [comment]
@Hokutosei you can stay with the 2.x line and things will keep working fine for you.

To update that sample code to 3.x, do the following:

```go
    token := jwt.New(jwt.SigningMethodRS512)
    claims := make(jwt.MapClaims)
    claims["exp"] = time.Now().Add(time.Hour * time.Duration(settings.Get().JWTExpirationDelta)).Unix()
    claims["iat"] = time.Now().Unix()
    token.Claims = claims
```

**Comment by dgrijalva** [comment]
OR
```go
    token := jwt.New(jwt.SigningMethodRS512)
    token.Claims = jwt.MapClaims{
        "exp": time.Now().Add(time.Hour * time.Duration(settings.Get().JWTExpirationDelta)).Unix(),
        "iat": time.Now().Unix(),
    }
```

**Comment by mikepc** [comment]
Without vendoring the dependency is there a way to keep it on the 2.x branch with go get? (like mgo.v2 ) ? How can I keep my existing api's in place and still use go get?

**Comment by dgrijalva** [comment]
From the readme:

While we try to make it obvious when we make breaking changes, there isn't a great mechanism for pushing announcements out to users. You may want to use this alternative package include: gopkg.in/dgrijalva/jwt-go.v2. It will do the right thing WRT semantic versioning.

-dave

**Comment by girgen** [comment]
How about this code from influxdata/influxdb, it has the same problem. My golang knowledge is not good enough to fully comprehend how to rewrite it:
```
keyLookupFn := func(token *jwt.Token) (interface{}, error) {
        // Check for expected signing method.
        if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
                return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
        }
        return []byte(h.Config.SharedSecret), nil
}

// Parse and validate the token.
token, err := jwt.Parse(creds.Token, keyLookupFn)
if err != nil {
        h.httpError(w, err.Error(), http.StatusUnauthorized)
        return
} else if !token.Valid {
        h.httpError(w, "invalid token", http.StatusUnauthorized)
        return
}

// Make sure an expiration was set on the token.
if exp, ok := token.Claims["exp"].(float64); !ok || exp <= 0.0 {
        h.httpError(w, "token expiration required", http.StatusUnauthorized)
        return
}

```

**Comment by dgrijalva** [comment]
The major change is when you read from `Claims`.  You need to typecast first.  `token.Claims.(jwt.MapClaims)["exp"]` should get you there, though that makes some assumptions.

**Comment by thakursaurabh1998** [comment]
I had a function which returned mapClaims like below:
```go
// decode.go
mapClaims := &token.Claims.(jwt.MapClaims)

// handler.go
name := *mapClaims["name"] // this gave me error that (type *jwt.MapClaims does not support indexing)

// This solved it for me
name := (*mapClaims)["name"]
