### ISSUE TITLE
Signing and verifying using HMAC

### ISSUE THREAD

**Issue by scorpnode** [dgrijalva/jwt-go#144]
Hi from what i understand I need to verify tokens, otherwise people can just sign and mimic the claims and it asks for 3 fields

signingstring
signature
key

Can you please explain the fields only one im sure of is the signature that is the 3rd portion of the token. 
Also, you mentioned something about "This allows you to use properties in the Header of the token (such as `kid`) to identify which key to use"
is the first field signingstring obtained from the signingstring function? You mentioned this is expensive. So if i have to verify tokens each time i have to use this expensive function?

Thanks

**Comment by scorpnode** [comment]
Does parse automatically verify so i dont have to use the verify method?

**Comment by dgrijalva** [comment]
Yes

-dave

**Comment by dgrijalva** [comment]
Check out https://jwt.io/introduction/ for an overview of how jwt works. Then have a look at the examples linked from the README here

-dave

**Comment by scorpnode** [comment]
thanks
