### ISSUE TITLE
Unable to decode my own custom map[string]interface{} type

### ISSUE THREAD

**Issue by pkieltyka** [dgrijalva/jwt-go#145]
I was trying to upgrade my https://github.com/goware/jwtauth HTTP middleware for jwt auth which uses this package, and came across an issue when I use my own map[string]interface{} type to decode a jwt token.

ie.

``` go
package mypkg

type Claims map[string]interface{}
// Claims to have its own methods, including Valid() error method

func decodeExample(tokenString string) (*jwt.Token, error) {
   t, err := jwt.ParseWithClaims(tokenString, Claims{}, keyFunc)
   return t, err
}
```

I consistently get an error for the same reason as the comment regarding the json decode special case. In my example, the code will hit:
https://github.com/dgrijalva/jwt-go/blob/master/parser.go#L58

one solution, is to just use jwt.Parse() without a custom claims, then wrap the type from as, `claims := Claims(t.Claims.(MapClaims))` .. which works, however, it will still enforce the Valid() method from MapClaims which I don't want.. so it's a bit more restrictive then what was previously suppoed in 2.x

let me know if you have any suggestions, but I believe the ParseWithClaims() methods needs to be reworked a bit to avoid that special case

**Comment by pkieltyka** [comment]
it may need some small use of reflect

**Comment by pkieltyka** [comment]
or.. by using a custom parser instead, as a copy/paste/minor-tweak into my library, which I think is a bit overkill. 

Another option, is to add `AutoValidateClaims bool` to the `jwt.Parser` struct which allows separating the verification of a jwt signature, from the validity of the claims. I wrote about it in first paragraph: https://github.com/goware/jwtauth/blob/master/README.md

**Comment by rjeczalik** [comment]
@pkieltyka Doesn't the below work for you?

```go
package yourpkg

type CustomClaims map[string]interface{}

func (cc CustomClaims) Valid() error {
    return jwt.MapClaims(cc).Valid()
}

func decodeExample(tokenString string) (*jwt.Token, error) {
    return jwt.ParseWithClaims(tokenString, &CustomClaims{}, keyFunc)
}
```

**Comment by pkieltyka** [comment]
@rjeczalik unfortunately not, give it a try. This is the reason for this issue.

**Comment by rjeczalik** [comment]
[I changed one of the parser's test-cases](https://github.com/rjeczalik/jwt-go/commit/8386ef3ddfd35584a37350667e9093bf54b6aa4d) to use CustomClaims:

```
$ go test -run TestParser -v .
2016/06/20 17:02:02 Listening...
=== RUN   TestParser_Parse
--- PASS: TestParser_Parse (0.03s)
PASS
ok  	github.com/dgrijalva/jwt-go	0.040s
```

Looks like it works.

**Comment by dgrijalva** [comment]
There is some special case code around `MapClaims` in the parse, having to do with they way interfaces point to maps vs structs.  I was worried this might come up.  Let me take another crack at making it work for any map type.

That said, `MapClaims` is pretty bare bones.  What features of Validate do you find too restrictive?

**Comment by pkieltyka** [comment]
@rjeczalik a map is already a pointer, so no need to make a pointer to a pointer as &CustomClaims{}. Similar, take a look at https://github.com/pkieltyka/jwt-go/commit/a0116a6b260873af24d0a7d305bb86cd0ac24a7b

the output is..

```shell
--- FAIL: TestParser_Parse (0.03s)
	parser_test.go:213: [basic] Claims mismatch. Expecting: map[foo:bar]  Got: map[]
	parser_test.go:217: [basic] Error while verifying token: *jwt.ValidationError:json: cannot unmarshal object into Go value of type jwt.Claims
	parser_test.go:245: [basic] Signature is left unpopulated after parsing
```

@dgrijalva this is just the first bug, and it should be solved, while keeping in mind that the custom map type should be able to have its own Valid() method, not because the default MapClaims.Valid() is too restrictive, but just because that is how an interface value should work, for any reason a developer may decide. Such as, related...

The second piece of feedback/issue is I don't think the Parse() methods should force validation of the claims, but instead it would be great if I could handle verifying the JWT signing in one call, and the validity of the claims in another call. My suggestion for this, as I mentioned previously, is to add a new field on the `Parser` struct called `ValidateClaims bool` with the default set to true (current behaviour). When set to false, it would be up to the developer to call t.Claims.Valid() on their own to validate the claims.

The use-case for splitting token verification and claims validation is in the case of jwtauth, I need to respond to the client differently depending on the error that occurs, and by a different part of the application. For example, if the token cannot be verified because the signature was signed with a wrong secret, then I will respond with a 401. However if the token verifies, but the claims have expired or breaks some kind of validation, I can redirect the user to a login page.

**Comment by rjeczalik** [comment]
> @rjeczalik a map is already a pointer, so no need to make a pointer to a pointer as &CustomClaims{}. 
@pkieltyka `json.Unmarshal` also requires map values to be passed as pointers: https://play.golang.org/p/2N7IqGhuOa.  Is there a use-case that would justify making the implementation of Parse more complex?

**Comment by pkieltyka** [comment]
@rjeczalik lol.. dude, thanks for the help, but its not very useful. https://play.golang.org/p/yC0YcDOkxZ .. which is the same as the code in the Parse() method. The bug, as mentioned in this title still stands, the ParseWithClaims() methods fails to fully support a custom map[string]interface{} type. Thanks and move on.

**Comment by ppknap** [comment]
@pkieltyka: Actually, @rjeczalik is right:

https://play.golang.org/p/H2eIkballl

**Comment by dgrijalva** [comment]
@pkieltyka there are several things here.  let me see if i can unpack:

* The whole pointer thing has to do with the interplay between maps and interfaces.  It's doesn't work as you'd expect, which is why there is a special case.  It's probably possible to make this work for all map types.  I didn't expect that to come up, so I only looked at the one.
* Parse will return the token, even if validation fails.  If you don't care about the validation part, you can ignore it.
* The error returned from Parse includes the reason it failed.
* If you wanted to open a PR for a feature that allows you to disable validation, I'd review it.  Validation needs to be on by default to avoid bad surprises with existing users.

**Comment by dgrijalva** [comment]
Here's an example of how to unpack the validation error that's returned by Parse: https://godoc.org/github.com/dgrijalva/jwt-go#example-Parse--ErrorChecking

**Comment by pkieltyka** [comment]
@dgrijalva @rjeczalik @ppknap I appreciate all the feedback and definitely one of the pains is the interplay between map and interface unmarshalling to work consistently like one would expect. The issue is without a bit of reflection, it's not possible to use a custom validation method on a map, I think thats clear tho and if you guys want, I can submit a PR to fix that prob with reflection.

@dgrijalva as for the other concern of separate token verification from claims validation, you're right that someone calling the Parse() method could ignore the err if a jwt.ValidationError were to occur, but just reading the code, there isn't a good separate of what is a claims validation error and what is a verification error. I'll try to find some time for a PR

third, I think the errors should be enumerated somewhere as variables, instead of composed ad-hawk in throughout functions, it helps for external packages to test the errors against known types.. something like..

```go
var (
   ErrInvalidSignature = errors.New("invalid signature")

   ErrTokenExpired = &ValidationError{Msg: "exp validation failed"}
)

type ValidationError struct {
  err error // original error
  Msg string
}

func (e *ValidationError) Error() string {
  return fmt.Printf("%s - %s", e.Msg, e.err.Error())
}
```

**Comment by dgrijalva** [comment]
Re: errors, have a look at the bitfield constants.

-dave

**Comment by pkieltyka** [comment]
for the separation of token parsing+verification and claims validation: https://github.com/dgrijalva/jwt-go/pull/146

**Comment by dgrijalva** [comment]
I poked at this for a while.  Turns out, it's pretty hard.  Go won't let you perform a type check on an interface type for a type that doesn't conform to the interface (to cast to `map[string]interface{}`).  Some type conversions are possible, but end up not working for various other interface/pointer interaction reasons I don't fully comprehend.  I haven't given up, but the solution is not going to be easy, or obvious.  I'll review #146 in the meantime.

**Comment by pkieltyka** [comment]
@dgrijalva thanks man. Yea, it is pretty hard to work with, perhaps the best is to offer control when necessary like in #146. I feel whenever a solution is becoming too complex, its better to look at the problem in a different way.

**Comment by dgrijalva** [comment]
I'm open to suggestions.  This is the best way we've come up with.

**Comment by pkieltyka** [comment]
since #146 has been merged, this issue isn't worth solving as you can use a custom map by wrapping it after the decoding process and validating there-after.
