### ISSUE TITLE
Unable to unit test casting MapClaims

### ISSUE THREAD

**Issue by cdelorme** [dgrijalva/jwt-go#149]
I am unable to write a unit test that validates scenarios where `token.Claims.(jwt.MapClaims)` would fail, since both resources are owned by jwt-go and cannot be abstracted.

A short chunk of code for context:

	func (self *Router) allowed(token *jwt.Token, permissions ...string) bool {

		if len(permissions) == 0 {
			return true
		} else if claims, ok := token.Claims.(jwt.MapClaims); !ok {
			return false
		} else if _, ok := claims["permissions"]; !ok {
			return false
		}

I cannot abstract `jwt.MapClaims` or `token.Claims` (as a property of `jwt.Token` and not a method) I am not sure how I should be getting code coverage for this.

Any suggestions?

**Comment by dgrijalva** [comment]
I don't understand what you're trying to do. Can you expand a bit?

**Comment by cdelorme** [comment]
Is there any scenario in which the Claims token property cannot be cast to a `jwt.MapClaims` type?

I am unable to figure out how to test it and get coverage for that conditional statement with `go test -cover` since I cannot abstract or control the Claims property or the MapClaims type.

---

In what scenario will `ok` not be true for this:

	_, ok := token.Claims.(jwt.MapClaims)

And how would you go about testing that in the function I provided?

**Comment by dgrijalva** [comment]
As a developer, you have total control over the type of `token.Claims`.  Tokens returned from the `Parse` method will always have a `MapClaims` object or nil.  The only way claims will be another type is if you use `ParseWithClaims`, in which case, you are specifying the type.

**Comment by dgrijalva** [comment]
`Parse` almost always returns a token, though it will be mostly unpopulated if parsing fails.  If you want to create a condition where `Claims` is nil, try `jwt.Parse("this.is.invalid", ...)`.  You should get a token with only the `Raw` property populated and a parse error.

**Comment by dgrijalva** [comment]
Also `Token` has no private fields, which means you can craft one any way you want for testing.  I think it's overkill, but go for it if you like.

If you want adequate coverage of handling the results of `Parse`, you need these things:
* Non-nil error returned
* Valid token, with a `MapClaims` object in `Claims`

**Comment by cdelorme** [comment]
@dgrijalva thank you very much for the suggestions and use-case explanation.  Using a raw token with no properties I was able to easily solve my tests.
