### ISSUE TITLE
Incorrect migration documentation

### ISSUE THREAD

**Issue by northbright** [dgrijalva/jwt-go#153]
Hi Dave,

It seems there're  some issues in the migration doc:

1. <https://github.com/dgrijalva/jwt-go/blob/master/MIGRATION_GUIDE.md#parsefromrequest-has-been-moved>
    * jwt.ParseFromRequest() / request.ParseFromRequest() has **NOT** "tokenString" parameter.
     
        * `jwt.ParseFromRequest(tokenString, req, keyLookupFunc);`
        * `request.ParseFromRequest(tokenString, request.OAuth2Extractor, req, keyLookupFunc)`

2. Should use jwt.MapClaims after request.ParseFromRequest()?

        if token, err := request.ParseFromRequest(tokenString, request.OAuth2Extractor, req, keyLookupFunc); err == nil {
            // Old
            // fmt.Printf("Token for user %v expires %v", token.Claims["user"], token.Claims["exp"])
            // New
            claims := token.Claims.(jwt.MapClaims)
            fmt.Printf("Token for user %v expires %v", claims["user"], claims["exp"])
        }

BRs,
Frank

**Comment by dgrijalva** [comment]
Thanks for catching this.  Someone opened a pull request with a fix for this, which I've just landed.
