### ISSUE TITLE
More properties in the CustomClaims?

### ISSUE THREAD

**Issue by Wstunes** [dgrijalva/jwt-go#157]
Now the custom claim is like this
type MyCustomClaims struct {
    Foo string `json:"foo"`
    jwt.StandardClaims
}
if I want more properties in the customClaims like
type MyCustomClaims struct {
    id string `json:"id"`
    tnt string `json:"tnt"`
    jwt.StandardClaims
}
when there are two or more properties in the custom claim, the jwt.newWithClaims() doesn't return the right Token.
How to deal with it please?
If the custom claims only support one property, what if I need two or more properties?
@dgrijalva

**Comment by falmar** [comment]
You need to export the Fields of your struct, otherwise it wont be visible for the "encoding/json" package and will be ignored when marshaling

Your **current** struct:
```go
type MyCustomClaims struct {
    id string `json:"id"`
    tnt string `json:"tnt"`
    jwt.StandardClaims
}
```

Should be:

```go
type MyCustomClaims struct {
    Id string `json:"id"`
    Tnt string `json:"tnt"`
    jwt.StandardClaims
}
```

**Comment by dgrijalva** [comment]
Resolved?

**Comment by Gilwe** [comment]
@dgrijalva can you please update the docs about using PascalCase when creating new properies for CustomClaims in https://godoc.org/github.com/dgrijalva/jwt-go#NewWithClaims ?

If you use camelCase it just won't be parsed
