### ISSUE TITLE
The encode method changed when the *Token is generated.

### ISSUE THREAD

**Issue by Wstunes** [dgrijalva/jwt-go#158]
Take an example:
if the claim has an Unix property like {"exp":1500000}
and when the Token is generated
token = jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
the tokenString is A.B.C
but after the token is parsed
and I extract the signingString(token.signingString)
it's A.B'
when I decode B' with Base64 , it's like {"exp":1.5e6} with scientific notation
The notation has been changed and it makes the verification with RS256 fail.
how to deal with it?

**Comment by dgrijalva** [comment]
The default behavior is the same as the default behavior of encoding/json, which is to say, all numbers are decoded as float64. If you cast your input type to match, it will test just fine. Alternatively, you can use the json number flag on Parser to use that behavior. 

-dave

**Comment by Wstunes** [comment]
But the RSA Verify method
func (m *SigningMethodRSA) Verify(signingString, signature string, key interface{}) error
It requires the signingString.
Since the signingString is different, so the verification always fails.
That's the problem. @dgrijalva

**Comment by dgrijalva** [comment]
I don't understand what you're trying to do

-dave

**Comment by Wstunes** [comment]
Let me explain the flow. I want to sign a JWT and Verify it with RSAMethod.
1. Create it a claim containing exp with Unix time.  claim := {"exp":1500000}
2.Create a jwt  token = jwt.NewWithClaims(jwt.SigningMethodRS256, claims) then sign it with private key. The tokenString is A.B.C
3. Parse the token with token :=Parse(tokenString string, keyFunc Keyfunc) (*Token, error) and get the *Token
4. Verify the token with func (m *SigningMethodRSA) Verify(signingString, signature string, key interface{}) error. This func requires signingString which is token.signingString. But now token.signingString is A.B'. And B' denotes {"exp":1.5e6}  which is different from the original claim.
When I pass the   token.signingString as parameter, the verification always fails.
That's the problem. @dgrijalva

**Comment by dgrijalva** [comment]
The token is verified as part of Parse.  You don't need to do it again.

**Comment by Wstunes** [comment]
I originally thought it works like that.
But it comes to an unpaired private/public key. The token returned by Parse func is still valid(token.valid is true). So I have to verify it again with func (m *SigningMethodRSA) Verify.
Maybe some errors in the Parse func when the method is RSA256?

**Comment by dgrijalva** [comment]
That shouldn't be the case.  Can you provide a failing test?

**Comment by dgrijalva** [comment]
Closing super hold ticket. Please feel free to reopen and provide a failing example. Thanks
