### ISSUE TITLE
token.go DecodeSegment could use RawURLEncoding(seg) instead of URLEncoding(seg + "===")

### ISSUE THREAD

**Issue by lahosken** [dgrijalva/jwt-go#160]
I sure am grateful for DecodeSegment which showed me what I was doing wrong when I tried to "roll my own" JWT decode: I didn't know about base64 padding.

Thanks to this code I read more about Go's base64 support and found out about base64.RawURLEncoding, which is like base64.URLEncoding, except it doesn't expect padding, so you don't have to add "=" characters to the end.

**Comment by dgrijalva** [comment]
I saw that.  I need to look into when those methods were introduced/published.  I'd like to switch to them, but it's not worth dropping go version support for it.

**Comment by dgrijalva** [comment]
We're going to drop support for some (TBD) old versions of go. Will switch to using these new methods.

**Comment by dgrijalva** [comment]
Fix landed in 4.0.0 branch

**Comment by lahosken** [comment]
YAY
