### ISSUE TITLE
StandardClaims.Id should be StandardClaims.ID

### ISSUE THREAD

**Issue by zvbuhl** [dgrijalva/jwt-go#163]
Per https://github.com/golang/go/wiki/CodeReviewComments#initialisms, 'Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case … This rule also applies to "ID" when it is short for "identifier," so write "appID" instead of "appId"'

https://github.com/dgrijalva/jwt-go/blob/master/claims.go#L21

It _is_ an API-breaking change.

**Comment by dgrijalva** [comment]
Yep.  Will put on the list for next time we break the API.

**Comment by weitzj** [comment]
Would it be feasible to make `golint` and `go vet` happy?
- Currently `go vet` shows only one error, whose fix requires no API change
- `go lint` clocks in 88 errors, whereas most of them are just missing comments. 14 of 88 are not related to comments:

```
claims.go:21:2: struct field Id should be ID
claims.go:99:9: if block ends with a return statement, so drop this else and outdent its block
claims.go:124:9: if block ends with a return statement, so drop this else and outdent its block
ecdsa.go:92:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
ecdsa.go:127:4: should replace keyBytes += 1 with keyBytes++
ecdsa.go:144:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
errors.go:26:2: const ValidationErrorId should be ValidationErrorID
rsa.go:97:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
rsa_pss.go:123:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
token.go:68:9: should omit 2nd value from range; this loop is equivalent to `for i := range ...`
cmd/jwt/app.go:62:9: if block ends with a return statement, so drop this else and outdent its block
cmd/jwt/app.go:193:10: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
request/extractor.go:78:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
request/request.go:21:9: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
```

**Comment by dgrijalva** [comment]
@weitzj probably.  More documentation is almost always better.  The other things look mostly stylistic.  I don't have a lot of religion around style.  I would like to avoid breaking API compatibility purely for stylistic reasons, though.

**Comment by dgrijalva** [comment]
@weitzj I'm starting to put together the next major revision. If you'd like to open a PR around improvements for the linter, now's a good time.

**Comment by JerryW007** [comment]
how i can change the config for ignore the spelling check

**Comment by dgrijalva** [comment]
This is landed in v4 branch
