### ISSUE TITLE
HMAC breaks if key is string

### ISSUE THREAD

**Issue by GeorgeLyon** [dgrijalva/jwt-go#164]
line 50 of hmac.go is where the problem lies. The key could be a string, causing the cast to []byte to fail. 

I'm using go v1.7

**Comment by dgrijalva** [comment]
HMAC expected `[]byte` keys.  You can just call `[]byte(myStringKey)` when passing the value in.

**Comment by GeorgeLyon** [comment]
Unless I'm missing something, jwt.Parse() accepts a string and I have no control over what happens down the line.

**Comment by dgrijalva** [comment]
`jwt.Parse()` accepts the raw token as a string and a lookup function that returns the key.  Each signing method requires a different key type.  For HMAC, it's `[]byte`.

**Comment by dgrijalva** [comment]
See https://github.com/dgrijalva/jwt-go/blob/master/hmac_example_test.go for an example implementation.

**Comment by GeorgeLyon** [comment]
Ahh, I see, I was thinking the key was the JWT. Thanks for the help
