### ISSUE TITLE
http_example_test.go error!

### ISSUE THREAD

**Issue by chris0927** [dgrijalva/jwt-go#174]
I use openssl for create a key 256:
         openssl genrsa -out app.rsa 256

run,print a error info:
crypto/rsa: message too long for RSA public key size

**Comment by dgrijalva** [comment]
That command generates a private key.  It looks like you're trying to parse a public key.  See https://rietta.com/blog/2012/01/27/openssl-generating-rsa-key-from-command/ for instructions on how to extract the public key from the private one.
