### ISSUE TITLE
Documentation/Examples needs a refresh

### ISSUE THREAD

**Issue by greenenergy** [dgrijalva/jwt-go#178]
Ideally, examples should compile so that you can test them out. Unfortunately, the examples refer to "hmacSampleSecret" without defining or explaining it, and the examples do not compile because of this.

**Comment by dgrijalva** [comment]
Are you sure you're looking at the current code?  The var you're referring to is both defined and explained.  The tests are executed by travis ci on every push.

From the most recent code: https://github.com/dgrijalva/jwt-go/blob/24c63f56522a87ec5339cc3567883f1039378fdb/hmac_example_test.go

```go
// For HMAC signing method, the key can be any []byte. It is recommended to generate
// a key using crypto/rand or something equivalent. You need the same key for signing
// and validating.
var hmacSampleSecret []byte
```
