### ISSUE TITLE
Feature request: Configure custom prefix string for tokens

### ISSUE THREAD

**Issue by basharov** [dgrijalva/jwt-go#185]
Tokens headers in my app look like so now:

`Authorization: Bearer <token>`

Currently I have to trim it this way: `pureTokenString := strings.TrimPrefix(tokenString, "Bearer ")`

Is it possible to set an option when initializing `jwt-go`, where I can set what prefix is?

So I could set prefix like `jwt.Prefix = "Bearer "` or `jwt.Prefix = "JWT "`.
Thanks!

**Comment by dgrijalva** [comment]
I'd like to keep the implementation on spec.  Trimming the token string is really more about the authentication protocol (OAuth, I assume) than the token.  There is a pretty helpful set of tools for extracting tokens from request.  See the `request` subpackage:

```go
    tokenString, err := request.OAuth2Extractor.ExtractToken(request)
```

**Comment by dgrijalva** [comment]
Closing this.  It should be trivial to implement what you want using the `OAuth2Extractor` as an example.  Feel free to reopen if you disagree.
