### ISSUE TITLE
Creating a new StandardClaims struct from MapClaims

### ISSUE THREAD

**Issue by basharov** [dgrijalva/jwt-go#186]
I am not sure if I am doing it correctly, but here is my scenario:

I generate a jwt token with the library then I try to create a new StandardClaims instance of it as it doesn't have all fields presented in the StandardClaims. I want to return this StandardClaims instance to the user.

    if claims, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
        stClaims := jwt.StandardClaims{Subject:claims["sub"].(string), ExpiresAt:claims["exp"].(int64)}
    }

What I see in the log when outputting the content of the `claims`:

```
&{eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0ODA0ODk2NTAsImlhdCI6MTQ3OTg4NDg1MCwic3ViIjoiamFja0BnbWFpbC5jb20ifQ.T7bSLRGZjUs750WSaMyPo1dpCaJTayzNqHFEGt4bqU8 0xc042006aa0 map[alg:HS256 typ:JWT] map[exp:1.48048965e+09 iat:1.47988485e+09 su
b:jack@gmail.com]
```

`exp` and `iat` are float64 so `exp` cannot be casted to int64 to be put as `ExpiresAt`.

Here is the error:

```
panic: interface conversion: interface is float64, not int64
```

When I use `jwt.Parser{UseJSONNumber:true}`, I still cannot convert to int64 from `json.Number`.

So, I assume, that when I generate a token, it puts numbers as floats and doesn't use them as int64 when parsing to MapClaims.

Here is how I generate the jwt token:

```
    token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.StandardClaims{
        Subject: userDb.Email,
        IssuedAt: time.Now().Unix(),
        ExpiresAt: time.Now().AddDate(0, 0, 7).Unix(),
    })
```

What am I doing wrong?

**Comment by dgrijalva** [comment]
JSON always represents numbers as `float64`.  That's why they end up that way when parsing into a map.  I don't totally understand what you're trying to do.  Could you not just parse directly into `StandardClaims`?

`jwt.ParseWithClaims(tokenString, &StandardClaims{}, keyfunc)` should do it.

**Comment by HouzuoGuo** [comment]
It's a Go quirk, once a large integer is serialised in scientific notation, json will never deserialise it into integer. So the serialisation process has to make sure integer numbers are written down, instead of the scientific notation.

**Comment by dgrijalva** [comment]
You can also enable to JSON Number flag, which uses `json.Number` instead of `float64` when decoding number values.

**Comment by eoinahern** [comment]
ran into the same issue.

**Comment by eoinahern** [comment]
any code examples  of how this is remedied?

**Comment by dgrijalva** [comment]
You want `int64(value)` instead of `value.(int64)`. See: https://play.golang.org/p/eoIZH5-un9s

If you use `json.Number`, you can use the [`Int64`](https://godoc.org/encoding/json#Number.Int64) method.
