### ISSUE TITLE
call api via javascript unauthorized (401)

### ISSUE THREAD

**Issue by emildd** [dgrijalva/jwt-go#191]
hi, anyone success call api bearer authorization via angular-resource ? 
I've tried from postman is no problem, but tried from angular is unauthorized and log is:
`[GIN] 2017/01/05 - 14:54:57 | 401 [0m|       9.967µs | ::1 |  [0m OPTIONS /api/v1/stream/test
Error #01: no token present in request`

my setting header example controller: 
`func (ctrl StreamController) Stream(c *gin.Context) {
	c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
	c.Writer.Header().Set("Access-Control-Allow-Headers", "Accept, Authorization")
	c.Writer.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS,PUT,DELETE")
	c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")
`

main package :
`
var secretString="secret"
apiv1 := router.Group("api/v1")
apiv1.Use(jwt.Auth(secretString))
apiv1.GET("/stream/:tag", streamController.Stream)
`
anyone solve the problem?

**Comment by dgrijalva** [comment]
This is probably not the right place for asking for angular help.
