### ISSUE TITLE
How to decode token to get current request user?

### ISSUE THREAD

**Issue by lehoai** [dgrijalva/jwt-go#193]
How to decode token (in header request) to get current request user?

**Comment by dgrijalva** [comment]
That really depends on your implementation.  This library focuses specifically on JWT tokens, rather than the whole OAuth spec.  JWT tokens are used in some, but not all, OAuth2 services but are also useful in many other contexts.

**Comment by dgrijalva** [comment]
There are several examples in the package documentation, including some that use oauth.

https://godoc.org/github.com/dgrijalva/jwt-go

Also, see the `request` subpackage that was created specifically for extracting tokens from http requests.  https://godoc.org/github.com/dgrijalva/jwt-go/request

**Comment by dgrijalva** [comment]
Gonna close this.  Feel free to re-open if you have further questions.
