### ISSUE TITLE
ValidationError number

### ISSUE THREAD

**Issue by thanhngvpt** [dgrijalva/jwt-go#199]
Hi all.
I have this code https://play.golang.org/p/Fru0oePFpA when accessing to path `/auth` to validate token. I always get error `2017/02/28 17:30:02 ValidationError error: 1`. What is the meaning of `1`? Many thanks.

**Comment by dgrijalva** [comment]
`ValidationError` complies with type `error`, meaning it has the method `Error()string`, which will return the error in human readable form.  The `Errors` field is a bitmask for storing details about what exactly went wrong.  The values are documented here: https://godoc.org/github.com/dgrijalva/jwt-go#ValidationError
