### ISSUE TITLE
Remove notice about vulnerability?

### ISSUE THREAD

**Issue by st3fan** [dgrijalva/jwt-go#201]
The README still says this:

> NOTICE: A vulnerability in JWT was recently published. As this library doesn't force users to validate the alg is what they expected, it's possible your usage is effected. There will be an update soon to remedy this, and it will likey require backwards-incompatible changes to the API. In the short term, please make sure your implementation verifies the alg is what you expect.

This vulnerability was published in 2015. If it has been addressed in go-jwt then maybe the notice should be removed?

**Comment by donatello** [comment]
I believe this refers to the `None` verification algorithm that is weirdly present in the JWT standard. This library still does not force the user to validate the alg sent in the token, and there is documentation encouraging users to do this. Additionally the `None` algorithm has been disabled default in this library [here](https://github.com/dgrijalva/jwt-go/blob/master/none.go#L32). It appears to be addressed, however I am no cryptographer. I would also appreciate clarity from the maintainer(s).

**Comment by dgrijalva** [comment]
I've updated the note as it's still worth mentioning.  As of 3.0.0, key types are not compatible across signing methods, which really helps.  It's still possible to get this wrong, so it's worth keeping a mention of it up front.

This satisfactory to close the ticket?

**Comment by donatello** [comment]
> This satisfactory to close the ticket?

IMO, yes.
