### ISSUE TITLE
crypto/rsa: message too long for RSA public key size

### ISSUE THREAD

**Issue by mickep76** [dgrijalva/jwt-go#213]
Using the example provided for RSA I keep getting the following error:

```
crypto/rsa: message too long for RSA public key size
```

From what I can understand it's because the payload is too large for the key size. Is there any plan's on supporting larger key sizes to solve this like 2048?

**Comment by dgrijalva** [comment]
It hasn't been requested, but is entirely possible.  If you look at `rsa.go` you can see how the existing three sizes are actually the same type with a different hashing function.  Last I worked on the RSA stuff, the JWT spec didn't define larger key sizes.  If you want to do something custom, it's fairly trivial to do so.  If the spec has evolved, I'd happily accept a pull request.

As a stopgap, you can define a custom type for your own use.  See the documentation for `RegisterSigningMethod`.

**Comment by mickep76** [comment]
Noticed the SHA512 is the maximum in the crypto package. Also this is only the signature, it turns out this was never the issue but rather the size of the RSA key I generated.

Increasing key size to 2048 solved the issue.
```
openssl genrsa -out priv.pem 2048
```
