### ISSUE TITLE
Release v3.0.1

### ISSUE THREAD

**Issue by VojtechVitek** [dgrijalva/jwt-go#221]
Hi,
can you please release v3.0.1 or any other version higher than v3.0.0 with the latest master commits included, especially c9eaceb2896dbb515dae7ec352b377a226a52721?

We'd like to use the latest release of jwt-go using https://github.com/golang/dep version constraints.

Best,
 -- Vojtech

**Comment by Xuanwo** [comment]
The same here, 3.0.0 is missing `parser.SkipClaimsValidation`.

**Comment by VojtechVitek** [comment]
@dgrijalva all we ask for is

```sh
git tag v3.0.1
git push --tags
```

Would you mind doing that, please?

**Comment by dgrijalva** [comment]
Sorry. I didn't see this.  I just cut v3.1.0.  Per semver, `SkipClaimsValidation` is a new feature, so it gets a minor version bump.

**Comment by VojtechVitek** [comment]
Thank you so much!
