### ISSUE TITLE
key is of invalid type

### ISSUE THREAD

**Issue by sredXNY** [dgrijalva/jwt-go#223]
Hi,I am using this great librry to decode the JWT token that I am receiving from another service. I made a simple example to check how it works and then I moved that code to my app. My situation is: I receive a JWT token and I have to extract some info from there, I need to have it in a map. So, I made this:

```
claims := jwt.MapClaims{}

	_, err := jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
		return []byte("Some verification key"), nil
	})

	if (err!=nil){
		fmt.Println("error parsing:",err.Error())
	}
```

In the example that I made, I had as verification key: `"<YOUR VERIFICATION KEY>"` but now I am getting an error: error parsing: `key is of invalid type`
Why am receiving that error if basically is the same? What value is accepted as a key?

**Comment by dgrijalva** [comment]
The key type is determined by the signing method.  A byte slice is
acceptable for the HMAC class of keys (HS256, etc), but not for all classes
of key.  Have a look at the 'alg' header value, then see the documentation
for that signing method.

**Comment by rkmax** [comment]
I also have a similar problem (go newbie here) the error dont give me a clue where I can start to debug, my setup it's pretty simple


I'm using the followin function to build the token

```go
func MakeToken() (string, error) {

	claims := &jwt.StandardClaims{
		ExpiresAt: time.Now().Add(time.Hour * time.Duration(1)).Unix(),
		Issuer:    "rkmax",
		IssuedAt:  time.Now().Unix(),
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	return token.SignedString([]byte("this is the sample key"))
}
```

now I did a simple handler to check if it's valid or not

```go
func VerifyUserHandler(w http.ResponseWriter, r *http.Request) {
	token, err := request.ParseFromRequest(r, request.OAuth2Extractor, tokenExtractor)
	if err != nil {
		fmt.Println(err)
		internal.JsonStatusResponse(err, w, http.StatusInternalServerError)
		return
	}

	if !token.Valid {
		internal.JsonStatusResponse(internal.ErrorResponse{"Unauthorized access"}, w, http.StatusUnauthorized)
		return
	}

	internal.JsonStatusResponse(internal.EmptyResponse{}, w, http.StatusNoContent)
}
```

my code always enter into the first err check, could you provide me some clue about what is wrong with my code @dgrijalva. thank you in advance for any help you might bring me

**Comment by rkmax** [comment]
Ok, I found the issue, changed tokenExtractor (maybe is not the best name because is keyFunc on arguments) to 

```go
func tokenExtractor(token *jwt.Token) (interface{}, error) {
	return []byte("this is the sample key"), nil
}
```

**Comment by dgrijalva** [comment]
Closing this as a duplicate. We definitely need better documentation around key types.
