### ISSUE TITLE
`func (e *ValidationError) valid() bool` should be public

### ISSUE THREAD

**Issue by AlmogBaku** [dgrijalva/jwt-go#229]
`func (e *ValidationError) valid() bool` should be public

**Comment by dharnnie** [comment]
Looks like it is.

**Comment by dgrijalva** [comment]
It's intentionally private. The library should never return a value where that returns true. It's used for internal bookkeeping during validation.

**Comment by AlmogBaku** [comment]
but what if you what to know what failed it?

**Comment by dgrijalva** [comment]
Check the error returned from Parse

-dave
