### ISSUE TITLE
asn1: structure error: tags don't match

### ISSUE THREAD

**Issue by MadMax411** [dgrijalva/jwt-go#231]
Hello! I use the following two lines of code to load a public.pem file (ALG=ES256). I don't have the private key. Only the public key to verify the token.

```
publicKeyFileContent, _ := ioutil.ReadFile("public.pem")
publicKey, err := jwt.ParseECPublicKeyFromPEM(publicKeyFileContent)
```

But I'm getting this error from jwt.ParseECPublicKeyFromPEM():
```
asn1: structure error: tags don't match (2 vs {class:0 tag:6 length:7 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @2
```

The content of the public.pem file:
```
-----BEGIN PUBLIC KEY-----
MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEehjijSZQATL8oSBPmOIV5eY9y7VnmMp3
eVgM+DjkYmT5vUckWNY0bZvYCXkxUuBgPJNuMBhagIrvgiR5DYih/Q==
-----END PUBLIC KEY-----
```

Where's my fault or is the public.pem file broken?

**Comment by dgrijalva** [comment]
It sure does look small. A 256 byte key, base64 encoded should be at least 342 characters. That's even without the typical structure of a PKCS encoded key.

**Comment by dgrijalva** [comment]
I haven't spent as much time with the EC keys as I have with RSA. I could be wrong, but I'd suspect the key.

**Comment by dgrijalva** [comment]
The other thing that's worth pointing out is that that's just a convenience method that implements parsing of the most common serialization format for keys. A key is just a big number, so there are lots of different ways it could be encoded. The JWT library just needs a `*ecdsa.PublicKey` to verify an EC256 token. How you get there is totally up to you. I'd look first at any documentation from the provider of that public key for hints on how it's encoded.

**Comment by MadMax411** [comment]
I tested the my token in this debugger: http://kjur.github.io/jsjws/tool_jwt.html

Copy the token in (step#3), the public.pem in (step#4) and press "verify it"

My token:
`eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImlkTWFuZGFudCI6NSwiVXNlcm5hbWUiOiJoYW5kd2VyayIsIkFucmVkZSI6IkhlcnIiLCJWb3JuYW1lIjpudWxsLCJOYW1lIjoiUENPIiwiRU1haWwiOm51bGwsInBlcm1pc3Npb25zIjp7fSwiZXhwIjoxNTA5NDAxNjcyLCJpYXQiOjE1MDk0MDEzNzJ9.UomKkCTwQpXXVWsBzlXzfdou3HNwWMckhNh-_aO61Daqq2ymBxpX_VuRUDviWaQbVvddE7dVbeOZFIxqbxecUg`

**Comment by dgrijalva** [comment]
Following those steps verifies it in "none" mode. You can modify the key and it will still say "valid"

**Comment by MadMax411** [comment]
So I need the values for X and Y to create the correct public key. The elliptic.Curce is elliptic.P256() in my case.

```
type PublicKey struct {
        elliptic.Curve
        X, Y *big.Int
}
```

**Comment by dgrijalva** [comment]
Probably. If you look at the helper method (https://github.com/dgrijalva/jwt-go/blob/master/ecdsa_utils.go), you'll see that it expects an x509 structure wrapped in a pem. You've got what looks like a valid pem containing some 88 bytes of data. What those bytes mean isn't obvious to me.

**Comment by MadMax411** [comment]
Sorry, I'm new to JWT. So I have to do more research on that topic and how to get the correct values from the public key file.

**Comment by niya3** [comment]
@MadMax411 Perhaps the wrong algorithm was used. I got the same error after using the pair that was generated by the command `openssl ... secp256k1 ...`, while `ES256` in the JWA specification assigned `ECDSA using P-256 and SHA-256` which means `secp256r1`
