### ISSUE TITLE
It would be nice to be able to leverage crypto.Signer.

### ISSUE THREAD

**Issue by nmaki** [dgrijalva/jwt-go#235]
I'd like to be able to use the library with the crypto.Signer interface instead of explicitly providing the private keys. This would allow for the signing secret to be stored in an HSM or behind some key management interface that doesn't directly expose the private bits.

Would there be interest in extending the current API to support performing the sign operations with just a crypto.Signer?

**Comment by dgrijalva** [comment]
Seems reasonable. When was crypto.Signer added to the language?

-dave

**Comment by nmaki** [comment]
It appears the interface was added a little over three years ago according to this commit https://github.com/golang/go/commit/7f2e68e9822ce8736d66035d0a3ed3677c2db459

In the spirit of compatibility we should be able to implement the SigningMethod by taking an opaque signer in place of the key.

**Comment by nmaki** [comment]
PR'd here https://github.com/dgrijalva/jwt-go/pull/236, go1.3 didn't have the crypto.Signer interface yet though so the build fails.

**Comment by nmaki** [comment]
If go1.3 compatibility is required we could probably use build tags to build as things were for 1.3 and use the crypto.Signer backed code for go1.4+. This would make things a little messier though.

**Comment by mtharp** [comment]
How about this?

https://github.com/mtharp/jwt-go/commit/a05b093176136b77c8b18d529a3b3b0255d6c125

Not too intrusive and passes tests. Personally I think supporting out-of-maintenance Go versions in a security-related project is probably a bad idea, but not my call.

**Comment by dgrijalva** [comment]
I've got some time set aside next week to look at a bunch of PRs. I'll add this to my list.

I think we can/should probably drop 1.3 support, but I would consider that a breaking change. What do you think the policy should be WRT old versions?

**Comment by mtharp** [comment]
Never mind about my patch, the tests do not pass after all and signing does not work at all on 1.3. I'm confused as to how it passed in Travis. The only way to continue supporting 1.3 would be to retain both the direct path as well as the Signer path.

Not sure what policy other projects use for dropping Go versions, but considering how long 1.3 has been out of support I don't think anyone could put up a compelling argument for keeping it. As for which versions to support, keeping obsolete versions until supporting it becomes a significant obstacle seems fine to me.

**Comment by dgrijalva** [comment]
We can do this as part of v4.

**Comment by dgrijalva** [comment]
This has landed on the v4 branch.
