### ISSUE TITLE
Can't access package documentation

### ISSUE THREAD

**Issue by dharnnie** [dgrijalva/jwt-go#239]
I tried to access the documentation on godoc.org. Turns out it (godoc.org) is down, and I can't find an alternative on golang.org/doc.

Any ideas on how to find the documentation on golang.org/doc?
Thank you.

**Comment by dgrijalva** [comment]
Looks like godoc is back up. 

If you did need to access go package documentation while offline, you can use the tools built into the language. See https://godoc.org/golang.org/x/tools/cmd/godoc for instructions on how to use the built-in documentation tools. These will produce the same results as godoc, save some formatting differences, and can be run locally, so long as you have the code already.

**Comment by dharnnie** [comment]
Yeah! My bad. godoc.org was never really down. The issue was really with my network. I accessed from a different network and it worked.
