### ISSUE TITLE
Should validate the signature before decoding the payload

### ISSUE THREAD

**Issue by thomdixon** [dgrijalva/jwt-go#241]
Signature validation is performed as [the last step](https://github.com/dgrijalva/jwt-go/blob/master/parser.go#L118), when in fact, it should probably be the next step after parsing the header to determine the signature type. This would allow you to bail early if the token is invalid, since the contents can't be trusted anyway.

**Comment by dgrijalva** [comment]
Fair point. It would be a little bit faster to process the signature first. This only matters if you're handling a very large volume of tokens with invalid signatures.

The trade-off is, this makes the content of the token unavailable to the key lookup function. In theory, this should not matter, since you shouldn't be looking in there yet. I worry that, in practice, this may make things challenging for some users. At a minimum, this would be considered a breaking change.

Are there any users out there who would be negatively impacted by this?

**Comment by dgrijalva** [comment]
Though, a half-measure would be to swap the order of validating the signature and the claims. It would only be marginally more performant, but would have no usage impact.

**Comment by thomdixon** [comment]
Sounds good to me. That will give a minor performance bump in the interim and give developers a chance to chime in if they would be negatively impacted by the breaking change.

If you're adverse to adding a breaking change, you could also let this just be a parser flag (e.g., `StrictValidation`) that fails without parsing the claims if the signature is invalid, which would let developers opt in to it.

**Comment by thomdixon** [comment]
Sounds good to me! Thanks for being so receptive! It's pretty refreshing.

**Comment by dgrijalva** [comment]
Sorry it took so long.

-dave

**Comment by someone1** [comment]
Will this break any use case where the `kid` found in the header is used to select the proper key for signature verification? See: http://self-issued.info/docs/draft-jones-json-web-token-01.html#ReservedHeaderParameterName

**Comment by thomdixon** [comment]
It shouldn't break that use case, because the header would still be parsed and the specified key should still used to validate the payload before the payload is parsed.

**Comment by tkinz27** [comment]
Will it still be possible to parse the claims before verifying the key? We switch based on the token issuer which key to return to validate the token with.

**Comment by dgrijalva** [comment]
Yes. Everything is parsed before calling keyfunc. We only changed the order that validations are applied.

That said, the spec suggests you should not do anything with the claims body until the signature is verified. The head section is supposed to contain all information necessary for signature validation.

**Comment by dgrijalva** [comment]
This has landed in v4
