### ISSUE TITLE
IssuedAt claim should not be validated.

### ISSUE THREAD

**Issue by pamburus** [dgrijalva/jwt-go#246]
Clock skew cannot be avoided in distributed systems.
So, IssuedAt claim cannot be validated correctly.

You can see discussions here:
https://github.com/jpadilla/pyjwt/issues/190
In short, 
1. auth0 implementations of JWT validation do not include validation of 'iat' claim.
2. RFC7519 does not require its validation.
3. Validation of 'iat' finally was removed from pyjwt.

**Comment by dgrijalva** [comment]
This is probably right. What do you think is the best way to change this without breaking things for people who expect the current behavior?

**Comment by umpc** [comment]
Because existing uses of this package are, or at some point were, tested against systems having no significant clock skew, and because specifically this feature may be used as part of various security implementations, in my opinion this isn't a change that should be made to a patch or minor version.

I think it should be changed too. Just chiming-in in case this would cause an accident for someone.

**Comment by buger** [comment]
I would say that removing validation at all can be a bad idea due to backward compatibility reasons, but making allowed clock scew configurable can solve this issue.

**Comment by riot-jayb** [comment]
Wouldn't it be backwards compatible if this was a configurable option to disable or set a clock drift tolerance? Then we could default to the old behavior and people with this problem can opt into the new config settings.

This issue has been plaguing me as well. Would be happy to assist on the code if we can agree on a path forward.

**Comment by danielchatfield** [comment]
Would we be able to set an allowed skew `time.Duration` which would default to 0 to maintain backwards compatibility?

**Comment by APTy** [comment]
+1 would like to see tighter conformance to the JWT spec, which places no restrictions on the "iat" claim. Any update on when this could be included in a future release?

**Comment by dgrijalva** [comment]
This is landed in v4

**Comment by adamgering** [comment]
Will this land in v3.2 as well?
