### ISSUE TITLE
RS256 panic

### ISSUE THREAD

**Issue by fantyz** [dgrijalva/jwt-go#25]
The example from the README fails with a panic when attempting to use `RS256` (the example is working if I switch to `HS256`):

```
// Create the token
token := jwt.New(jwt.GetSigningMethod("RS256"))
// Set some claims
token.Claims["foo"] = "bar"
token.Claims["exp"] = time.Now().Add(time.Hour * 72).Unix()
// Sign and get the complete encoded token as a string
tokenString, err := token.SignedString(mySigningKey)
```

Panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x438ef7]

goroutine 1 [running]:
runtime.panic(0x60a960, 0x8a4b28)
    /usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/dgrijalva/jwt-go.New(0x0, 0x0, 0x0)
    /home/kmp/go/src/github.com/dgrijalva/jwt-go/jwt.go:39 +0x27
main.main()
    /home/kmp/projects/playground/googleapi.go:25 +0x54
exit status 2
```

**Comment by skyl** [comment]
Odd that I had and example running fine the other day with RS256. I come back a couple of weeks later and I get `Error signing token: Invalid Key: Key must be PEM encoded PKCS1 or PKCS8 private key`. Switching to `HS256` makes the service return a token as expected. I haven't changed anything and thought I had all of my dependencies pinned 🤔

**Comment by dgrijalva** [comment]
Interesting.  The `HS` family of signing methods take a byte slice as a key. It doesn't really care what the contents are. The `RS` family depend on valid public and private RSA keys.

The older version of this library will attempt to auto-parse a byte slice using a few most common encodings. It was determined this behavior made it easier to make certain mistakes when implementing a solution with this library.

The 3.x line no longer automatically attempts to parse a byte slice. Instead, you must pass in a valid `rsa.PublicKey` or `rsa.PrivateKey` for validating or signing, respectively. The PEM parsing behavior was moved to a helper function.

In any event, there are a myriad of techniques for serializing keys. The most reliable solution is to understand how your keys are serialized and use the appropriate technique for parsing, then use the `rsa` types with this library. On top of being more forward compatible, it removes some magic that might not be working quite right for you.
