### ISSUE TITLE
How to validate signature on expired token.

### ISSUE THREAD

**Issue by niocncn** [dgrijalva/jwt-go#251]
What is the best way to check than JWT token has valid signature, but may be expired few days ago. 
I'm making refresh route in my app.
When I parse token like this
```
var claims Helpers.JwtCustomClaims
tkn , err := jwt.ParseWithClaims(token, &claims, func(token *jwt.Token) (interface{}, error) {
	return []byte("*****")), nil
})
```
, I have `token is expired by 2h57m47s` error, and `tkn.Valid == false`.
It seems to me checking `err` for substring `token is expired by ` is not the best solution.

**Comment by niocncn** [comment]
Nobody did it? Really?

**Comment by umpc** [comment]
In Go, you would want to assert the returned error value as a ```*jwt.ValidationError``` type and then compare its exported Errors field to the types of errors that you are looking for, listed as constants here: https://godoc.org/github.com/dgrijalva/jwt-go#pkg-constants

For more info, this blog post is helpful: https://blog.golang.org/error-handling-and-go

**Comment by niocncn** [comment]
Thanks! 
I did it like this

```
	var claims Helpers.JwtCustomClaims
	_ , err := jwt.ParseWithClaims(token, &claims, func(token *jwt.Token) (interface{}, error) {
		return []byte(Helpers.GetConfig("JWT_SECRET","***")), nil
	})

	v, _ := err.(*jwt.ValidationError)

	if v.Errors == jwt.ValidationErrorExpired && claims.ExpiresAt > time.Now().Unix() - (86400 * 14){
		/** refresh logic **/
	}
```

**Comment by odino** [comment]
@niocncn I think you might need to first check the token without claims, in the source code of the library I see it firsts validates the claims and eventually performs the validation of the token:

https://github.com/dgrijalva/jwt-go/blob/master/parser.go#L62-L80

In your case I think you might run the refresh logic even if the token did not have a valid signature.

**Comment by odino** [comment]
Actually, my bad: I see the signature is [anyhow checked before returning](https://github.com/dgrijalva/jwt-go/issues/114#issue-126745116) -- sorry for alarming! :)

**Comment by markschmid** [comment]
@niocncn This is helpful, thanks.
Quick question: why do you check claims.ExpiresAt for 14 days ago? Is ```v.Errors == jwt.ValidationErrorExpired``` not enough to check if it is expired?

> ```
> 	if v.Errors == jwt.ValidationErrorExpired && claims.ExpiresAt > time.Now().Unix() - (86400 * 14){
> 		/** refresh logic **/
> 	}
> ```
