### ISSUE TITLE
Critical vulnerabilities in JSON Web Token libraries

### ISSUE THREAD

**Issue by ChadTaljaardt** [dgrijalva/jwt-go#252]
Im not sure if this is relevant but i came across this article on jwt.io and i'm not sure if this package is affected or not?

https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

Thanks!

**Comment by dgrijalva** [comment]
There's been some discussion of this before. See the Security Notes at the top of the README file. tl;dr: As long as you verify the signing method matches your expectation, you should be fine. This library attempts to make it easy to do the right thing while keeping it possible to do less standard things. If you follow the examples, you should be fine.

**Comment by ChadTaljaardt** [comment]
Sorry i never saw the notice. 

thanks for your response and suggestion!

**Comment by dmaze** [comment]
Would you consider (a) adding the security note to `doc.go`, (b) removing the `jwt.Parse` and `jwt.ParseWithClaims` top-level functions, and (c) erroring at https://github.com/dgrijalva/jwt-go/blob/master/parser.go#L30 when `ValidMethods` is `nil`?

It seems a little tricky to me to find the actually-secure way to use this library, and if you're starting from _e.g._ https://godoc.org/github.com/dgrijalva/jwt-go and aren't already familiar with this issue, it seems very easy to find a "parse" method that has this vulnerability.
