### ISSUE TITLE
Expiration check troubles with ParseUnverified

### ISSUE THREAD

**Issue by sevagh** [dgrijalva/jwt-go#268]
Hello,

I have a JWT token which, when I enter into jwt.io debugger, gives me the following expiry date:

```
{
  "exp": 1527035340,
```
In human time, this is `05/23/2018 @ 12:29am (UTC)` (so, this token should already be expired, correct?)

Also, when using this token with the Postgrest endpoint, it returns:

```
{"message":"JWT expired"}
```

In my code I have the following expiration check (using this library):

```go
func isTokenExpired(tokenString string) bool {
        fmt.Printf("The token is:\n%s\n", tokenString)
	var p jwt.Parser

	_, b, err := p.ParseUnverified(tokenString, &jwt.StandardClaims{})

        for _, p := range b {
                fmt.Printf("%s\n", p)
        }

	switch err.(type) {
	case *jwt.ValidationError:
		vErr := err.(*jwt.ValidationError)
		switch vErr.Errors {
		case jwt.ValidationErrorExpired:
			return true
		default:
			return false
		}

	default:
		return false
	}
```
When parsed, the err is always `nil`. Can you advise on what I'm doing wrong here?

I want to check if the token is expired before prompting the user to generate a new one.

**Comment by johnaoss** [comment]
To my knowledge, ParseUnverified doesn't check if the token is expired or not. If you still want to use ParseUnverified over Parse, you could add a check against `token.Claims.Valid()`, but that requires you storing a Token pointer.

**Comment by sevagh** [comment]
Does the expiration time parsing really require signature verification also? Or is it just an oversight in this library?

**Comment by dgrijalva** [comment]
`ParseUnverified` intentionally performs little validation. It just parses the token. It exists mostly to assist with debugging. As others have mentioned, you can access the claims validation code directly with `token.Claims.Valid()`.

In general, there should be few cases where you want to do this outside of testing/debugging. The contents of a token are meaningless if the signature is invalid.

**Comment by sevagh** [comment]
Thanks. My intention was for a client to check if it's locally cached JWT is expired, to ask the user to re-login, before making a request to the upstream server that fails due to the JWT being expired - so it's a case where:

1. Local client doesn't have the signing key so it can't verify any real signature
2. It just needs to know the expiry time

Just a convenience but I don't need to have it.

**Comment by dgrijalva** [comment]
That makes sense. You should be able to get there with `ParseUnverified` and `token.Claims.Valid()`.

**Comment by sevagh** [comment]
I believe `token.Claims.Valid()` works. Thanks for the suggestions!
