### ISSUE TITLE
cannot install jwt go via "dep"

### ISSUE THREAD

**Issue by AlaaAttya** [dgrijalva/jwt-go#269]
i'm trying to install the package using this command 

`dep ensure -add  gopkg.in/dgrijalva/jwt-go.v3 `

the output is 
```
"gopkg.in/dgrijalva/jwt-go.v3" is not imported by your project, and has been temporarily added to Gopkg.lock and vendor/.
If you run "dep ensure" again before actually importing it, it will disappear from Gopkg.lock and vendor/.
```

but when i check the vendor folder i could not find the packages files and when i run `dep ensure` the package is being remove from the `.lock` file

**Comment by dgrijalva** [comment]
This is part of how dep works. Dep actually looks in your project source
and will only pull in projects that are actually used. Dep is also
compatible with semver projects on github. Try this:

1) import github.com/dgrijalva/jwt-go somewhere in your project
2) dep ensure -add github.com/dgrijlava/jwt-go@^3.0.0

-dave

**Comment by AlaaAttya** [comment]
@dgrijalva yes that make it work, thanks 👍
