### ISSUE TITLE
Requests Subpackage Not Supported by gopkg.in

### ISSUE THREAD

**Issue by upsampled** [dgrijalva/jwt-go#270]
The README recommends grabbing the V3 version of the code at `gopkg.in/dgrijalva/jwt-go.v3`.  

`go get gopkg.in/dgrijalva/jwt-go.v3` and `import jwt "gopkg.in/dgrijalva/jwt-go.v3"` works for the main `jwt` package but will not work for the `requests` sub package as it performs an absolute import on the main `jwt` package via github. 

I found this out by running `http_example_test.go` and the compiler erroring that  requests.ParseFromRequestWithClaims was not finding the "github.com/dgrijalva/jwt-go" import.

**Comment by upsampled** [comment]
Never-mind this is now working for me

**Comment by upsampled** [comment]
I falsely closed this due to a cached library

**Comment by dgrijalva** [comment]
This is a limitation of the gopkg.in tool, which I don't maintain. With tools like dep quickly becoming mainstream, I'd prefer to target those. gopkg.in will continue to work as long as the maintainer keeps it running, but I'm going to remove it as a recommendation for future versions of this library.
