### ISSUE TITLE
asn1: structure error ... signing by RS256 and verifying with public key

### ISSUE THREAD

**Issue by OscarZhou** [dgrijalva/jwt-go#271]
My situation is that I used `RS256` to sign and `publickey.pem` to verify. Signing works, but verifying doesn't.

I noticed that in the function `ParseRSAPublicKeyFromPEM` in the `rsa_utils.go` file:

```
if parsedKey, err = x509.ParsePKIXPublicKey(block.Bytes); err != nil {
		if cert, err := x509.ParseCertificate(block.Bytes); err == nil {
			parsedKey = cert.PublicKey
		} else {
			return nil, err
		}
	}
```

`PKIX` is the method used to parse the public key here, but the problem is that my public key is generated by `PKCS1`. The data struct is totally different from the one in `PKIX`. If I replaced `x509.ParsePKIXPublicKey(block.Bytes)` with `x509.ParsePKCS1PublicKey(block.Bytes)`. It will work.  

I am wondering if I must use the certificate to verify the JWT?  

I tried both of option `public key` and `certificate` to verify JWT. The certificate option works, as it goes to `x509.ParseCertificate(block.Bytes)`. But the public key option can not be parsed by either `x509.ParsePKIXPublicKey(block.Bytes)` or `x509.ParseCertificate(block.Bytes)`.

Thanks.

**Comment by johnaoss** [comment]
How are you generating your public key?

**Comment by johnaoss** [comment]
@OscarZhou I had the same problem when running the original example. That post stores the data inside the PEM as raw ASN.1.  Earlier in the example, the private PEM is created with ASN.1 DER-encoded internals. Additionally, most packages that deal with certificates deal with them in DER encoded formats.

The solution is changing `asn1Bytes, err := asn1.Marshal(pubkey)` to`asn1Bytes, err := x509.MarshalPKIXPublicKey(&pubkey) ` as previously suggested by @Xeoncross

**Comment by OscarZhou** [comment]
@johnaoss Yes, maybe it is a better solution than replacing `x509.ParsePKIXPublicKey(block.Bytes)` with `x509.ParsePKCS1PublicKey(block.Bytes)`. Thanks. I will close this question.
