### ISSUE TITLE
A better way to expire an existing token

### ISSUE THREAD

**Issue by miguelpragier** [dgrijalva/jwt-go#273]
Hi!

I need to send back to browser the same token it has sent me, but forcibly expired.

To force expiration of the current token, I'm taking this token and: 
- parsing it with jwt.Parse()
- Checking validity si token.Valid
- Gettin' the claims with token.Claims.()
- Creating a new token with the same claims, but with "exp" = time.Now().Unix()

**Is there a better way?**

Best Regards

**Comment by dgrijalva** [comment]
That approach will work, though I've never seen a scenario where this was a useful thing to do. I'd be curious to know the use case here, if you feel like sharing.

**Comment by miguelpragier** [comment]
Hi, Dave!
The frontend app ( outside my domain ) got a interceptor that requires the token even for logout. So I expire the token before give it back.
And I don't create a new one because my environment is 100% impersonated at this point.

So as you see, it's not a big thing, no much more than a workaround :-)

Thank you very much for your time and congratulations for this great jwt work!
