### ISSUE TITLE
Subsecond values discarded

### ISSUE THREAD

**Issue by pascaldekloe** [dgrijalva/jwt-go#282]
The parser incorrectly discards resolutions smaller than a second. Numbers in JSON are (double-precision) floating-points. Also RFC 7519 explicitly mentions the applicability with "non-integer values can be represented". The rounding causes "nbf" violation.

**Comment by dgrijalva** [comment]
Good catch. I believe this will be resolved with the switch to a smarter type for time values in v4.

**Comment by dgrijalva** [comment]
This is resolved on v4 branch.

**Comment by pascaldekloe** [comment]
The NewTime float64 conversion is still imprecise and complicated @dgrijalva. Please have a look at <https://github.com/pascaldekloe/jwt/blob/master/jwt.go#L277>.

**Comment by dgrijalva** [comment]
Yeah. That’s better. Thanks.

-dave

**Comment by pascaldekloe** [comment]
Still there, please reopen the issue so that this won't be lost.

**Comment by dgrijalva** [comment]
just got back to my computer. landed the change
