### ISSUE TITLE
Getting 'key is of invalid type' when trying to ParseWithClaims

### ISSUE THREAD

**Issue by jennyphan** [dgrijalva/jwt-go#283]
I am trying to parse a JWT Token and I keep getting 'key is of invalid type'.  I think that the encrypted key that I am passing in is invalid but I have tried so many different key values.  I am using Azure B2C and I retrieved the public key but that did not work.  I also used the kid value in the header and the secret key created in Azure for my registered apps.  I am unable to resolve this issue.  I am using RSA256. Variations of the key that I have tried

encryptedKey := "-----BEGIN CERTIFICATE-----xxxxxxxxxxxxxxxxxxxxxx-----END CERTIFICATE-----" where xxxxxx is public key from Azure
encryptedKey := kid value from request header
encryptedKey := secret key created in Azure Portal for my web api

	token2, err := jwt.ParseWithClaims(token.AccessToken, &User{}, func(token *jwt.Token) (interface{}, error) {
		return []byte(encryptedKey), nil
	})

**Comment by jennyphan** [comment]
This was a type issue with golang, I converted to the correct type and it is working.

**Comment by ernsheong** [comment]
@jennyphan what was the type issue?
