### ISSUE TITLE
Best practice of storing token?

### ISSUE THREAD

**Issue by superarts** [dgrijalva/jwt-go#291]
Hi I'm new to back-end field, previously I was using `Vapor` and it generates a random token when user logs in, and store it in database. Now when I start working with `golang`, I found this JWT library and have some noob questions:

1. Suppose if server secret is leaked, is anyone going to be able to login with any username? And vice versa, is it true that without server secret, a hacker is mathematically never able to login as other user, without saving any information on the server side?
2. If I ever want to save the generated token to my database, any recommended libraries to help me to do that? (This should be super easy but just curious if there's any library that offers better overall design; don't want to re-invent the wheels)
3. Is there any recommended library that handles passport storing? (Something like [this](https://medium.com/@jcox250/password-hash-salt-using-golang-b041dc94cb72), again it shouldn't be hard but not sure if there's anything already exists.)

Thanks!

**Comment by dgrijalva** [comment]
There's a lot of good writing out there about how to use bearer tokens (such as JWT) securely. I'd rather not be too prescriptive as it's beyond the scope of this library.

That said, tokens should be treated as secrets. You can't really hash them (like passwords) without them becoming useless. Ideally, tokens are short lived and you have a strategy in place for handling leaked tokens or token secrets. The OAuth 2 spec provides some decent solutions to help keep your tokens ephemeral.

The secrets used to sign tokens should be treated with the same care you give to things like SSL private keys, because leaked secrets can be catastrophic.

**Comment by superarts** [comment]
Thanks @dgrijalva , just one more thing about ephemeral token: suppose the business requirement is that user never needs to enter his username and passport again, even he hasn't been using the app for a long time, let's say a month. 

In this case, it seems to me that no matter what kind of mechanism has been implemented, like expire token in 1 hour but allow it to be used for renewal for a month, it doesn't help to make the system more secure. Because the whole point of short-life token is that even hacker gets the token, he can only perform attack in a short time window; but in the case mentioned above, hacker can still refresh the token, and get the most recent one.

So, I wonder how the system is more secured with the whole expire/refresh approach. To me it is impossible to differentiate "user tries to use the app again after a month" and "hacker tries to perform attack using a token he got 1 month ago". My apologize if this question is too basic, but answers like [this](https://security.stackexchange.com/questions/113273/how-does-a-refresh-token-help) are just not convincing enough (like the attack mentioned in the answer can simply be identified using IP address checking for the same user).

**Comment by dgrijalva** [comment]
This question is outside the scope of this library. This library is concerned with the creation, parsing, and validation of tokens. This question is more about their usage in a larger authentication protocol. That said, here's my _opinion_:

Use different tokens. Your authorization token should be short lived. Create a second, 'remember' token with a longer expiration time, or -ideally- use another means of invalidation that can be implemented server side. The remember token should _only_ be valid for getting an auth token. Client side, it should be treated like a password. 

The benefit of this approach is, you can have fast path (state-free if using asymmetric signing method) authentication for all requests except for refreshing your access token, but still have a solution for remotely disabling a remember token.

**Comment by dgrijalva** [comment]
@superarts ^^

**Comment by superarts** [comment]
Thanks, performance reason is convincing. Sorry to keep bring this out-of-scope question here ^.^
