### ISSUE TITLE
JWT secret base64 encoded

### ISSUE THREAD

**Issue by uded** [dgrijalva/jwt-go#303]
OK, I am most probably doing something wrong, but I can't make a JWT token with HSA512 and base64 encoded secret that will validate against jwt.io

Any solution?

**Comment by shajalahamedcse** [comment]
Can you send any error log ? So that anyone can look around .

**Comment by uded** [comment]
Well, not much of a log on this level. But I tried to sign the token with:

```
	Secret := Babase64.URLEncoding.EncodeToString(secret)   
	tokenString, _ := token.SignedString([]byte(Secret))    
```

Just a simple test. I did more variations of this code and I was never able to get jwt.io to confirm that the token has a valid signature...

**Comment by uded** [comment]
Any clues to what I am might be doing wrong?

**Comment by edwardfward** [comment]
Try removing any encoder padding. I encountered the same issue validating the example signature in RFC 7519. 
```go
b64Secret := base64.URLEncoding.WithPadding(base64.NoPadding).EncodeToString(secret)
```

**Comment by uded** [comment]
This case can be closed. Well, guess what - it was a mistake on my end in a way. Or, rather, misunderstanding on how jwt.io works with them vs. the library...

**Comment by gimox** [comment]
same problem here!

**Comment by connectkushal** [comment]
> This case can be closed. Well, guess what - it was a mistake on my end in a way. Or, rather, misunderstanding on how jwt.io works with them vs. the library...

@uded Hey thanks for creating this issue, could you please elaborate on what you found out regarding how jwt.io works vs the library ?

**Comment by connectkushal** [comment]
I was facing the same problem. After much trial and error I realized the correct understanding, for validating it on jwt.io, is that the "secret" is NOT base64 encoded when creating the token using this library. When you test the generated token using jwt.io debugger, you can either enter your secret string or if you want to be extra sure that it is not leaked, you can encode your secret into a base64 string and then tick the checkbox indicating you entered an encoded string of your secret. Hope this info saves someones time.
