### ISSUE TITLE
Key is of invalid type.

### ISSUE THREAD

**Issue by anamshah** [dgrijalva/jwt-go#304]
I am using ES256 as signin method. And i am getting the error. "**Key is of invalid type.**

Here is my code. 

```
token := jwt.New(jwt.SigningMethodES256)
token.Header["kid"] = config.KEY_IDENTIFIER

claims := make(jwt.MapClaims)
claims["iss"] = config.ISSUER // setting one month expiration to token
claims["aud"] = config.JWT_AUDIENCE
claims["exp"] = time.Now().Unix() + 1200 // adding when the token created
fmt.Println(claims)

token.Claims = claims

tokenString, err := token.SignedString([]byte(config.JWT_SECRET_KEY))

if err != nil {
fmt.Println(err.Error())
}

```

Please provide me proper example to solve.

**Comment by gustavooferreira** [comment]
I was getting the same RSA.

In my case, even though the documentation says it expects an RSA key, what it actually expects is a pointer to that.
In your case it might be the same.

**Comment by dgrijalva** [comment]
The library will not automatically parse your key from a byte slice. For `ES256`, I believe you need to provide a key of type `*ecdsa.PrivateKey`. As of v4, this will also accept a `crypto.Signer` so long as it produces a valid signature for that signing method.
