### ISSUE TITLE
Refreshing token freezes the middleware

### ISSUE THREAD

**Issue by j0hnwhyte** [dgrijalva/jwt-go#310]
Hi, I'm making some tests with the library, and it works fine. One issue I'm having is when making an invalid request for refreshing the token.

The request is `GET /auth/refresh_token` which I've mapped to the `RefreshHandler` middleware. As soon as I launch the request, I can see in the debugger that it stops in this line:

```go
	claims := token.Claims.(jwt.MapClaims)
```

There is no token defined in the request, it seems that the library doesn't handle this exception. Is it a bug?

Thanks

**Comment by lansana** [comment]
Not sure what your issue is, but you can easily avoid a "freeze", aka likely a panic, by modifying your casting code a bit from this:

`claims := token.Claims.(jwt.MapClaims)`

To this:

```
claims, ok := token.Claims.(jwt.MapClaims)
if !ok {
    // Error casting, handle error
}
```

**Comment by j0hnwhyte** [comment]
..of course. I was new to the language, and didn't think about the `ok` option.
