### ISSUE TITLE
ParseFromRequest

### ISSUE THREAD

**Issue by FelixMH** [dgrijalva/jwt-go#316]
I try to use ParseFromRequest() method, but I get a error that I can't solve.

This error it's : Cannot use ..... keyFunc in argument to Request.ParseFromRequest

I tried all and I've can't solve it, 

I used to do this: 

/*token, err := request.ParseFromRequestWithClaims(
		r,
		request.OAuth2Extractor,
		&models.Claim{},
		func(t *jwt.Token) (interface{}, error) {
			return commons.PublicKey, nil
		},
	)*/

and I try to do this: 

token, err := request.ParseFromRequest(
			r,
			request.OAuth2Extractor,
			jwt.Keyfunc(
				func(t *jwt.Token)(interface{}, error) {
					return commons.PublicKey, nil
				},
			),
			nil,
		)

But I can't use it.. because the errors jump to my terminal. 

I hope that someone helps me.

**Comment by dgrijalva** [comment]
Can you post the error you are getting?

**Comment by FelixMH** [comment]
This is the error that I getting : 

![Image -  error index out of range](https://i.ibb.co/4Y2qF9n/error-indexoutofrange.png)

I tried to post a comment with the API and this is the error that I have. 

I hope a help to you, I have so much weeks with this issue.

**Comment by FelixMH** [comment]
the error is Index out of range..

**Comment by FelixMH** [comment]
this is the code where I have the error ... 

db.Model(&comment).Related(&comment.User)
	comment.User[1].Password = ""

because of that is the index out of range...

**Comment by dgrijalva** [comment]
This doesn't look like it's related to this library, but I'd wager you are seeing that panic because `comment.User[1]` does not exist. You should probably put some validation code in there to verify the value is present before you attempt to use it.

Closing this ticket as it appears unrelated. If you believe that's not the case, please feel free to reopen.

**Comment by FelixMH** [comment]
I'm able to understand that this error  it's because the comment.User[1] doesn't exist. 

Before when ParseFromRequestWithClaims wasn't deprecated 
this error didn't get out for my api.

**Comment by FelixMH** [comment]
the code in the top it's how before I used it but now I am force to use ParseFromRequest and I don't know how can I replace "ParseFromRequestWithClaims" with ParseFromRequest, it's the only part of my code that getting panic.

**Comment by dgrijalva** [comment]
You can use `ParseFromRequest`, passing `WithClaims(myClaims)` as the last argument.

**Comment by dgrijalva** [comment]
Alternatively, you can use the request package to extract the token string from the request, then use any of the tools in the main (jwt) package.

**Comment by FelixMH** [comment]
I tried to pass the WithClaims and I getting panic too. I don't know what is the error getting because before the last version I don't remember which, was ok.
