### ISSUE TITLE
Not sure how to get Claims after Token is expired

### ISSUE THREAD

**Issue by mdere-unbound** [dgrijalva/jwt-go#319]
so my overall goal is to refresh the JWT token but I want to confirm things inside the Claim of the original expired JWT token before the system proceeds issuing a new JWT token.

`	token, err := jwt.Parse(input.Token, &Claims{}, func(token *jwt.Token) (interface{}, error) {`
....where input.Token is an expired Token 

then:

`f claims, ok := token.Claims.(jwt.MapClaims); ok { ....`

But I keep on getting  Errored refreshing token due to: token is expired by 15h47m16s.

Am I going in the right direction to get Claims of an expired Token?

**Comment by mdere-unbound** [comment]
ok after some searching....maybe my needed approach is this??

https://github.com/dgrijalva/jwt-go/issues/251

**Comment by dgrijalva** [comment]
You should be able to use ParseUnverified to look at the contents of an expired token. That said, you probably should not be reissuing tokens from expired ones.
