### ISSUE TITLE
Change format json response

### ISSUE THREAD

**Issue by putrafajarh** [dgrijalva/jwt-go#320]
How can i change this format response to my own format 

```
{
  "message": "invalid or expired jwt"
}
```

i want to change something like this

```
{
  "meta": {
    "status": false,
    "message": "Unauthorized",
    "messages": null
  },
  "result": null
}
```

i cant find how to do it

**Comment by dgrijalva** [comment]
I don't think I understand what you're trying to do. Could you please elaborate?

**Comment by dgrijalva** [comment]
Closing ticket. If you would like to follow up, please feel free to reopen.
