### ISSUE TITLE
my claims have slicie members,and they can not be parse

### ISSUE THREAD

**Issue by birdycn** [dgrijalva/jwt-go#322]
```
type Claims struct {
	Username string `json:"username"`
	Password string `json:"-"`

	UserID     uint       `json:"userID"`
	Roles      []Role     `json:"roles"`
	Businesses []Business `json:"businesses"`

	ClientIp string `json:"clientIp"`
	jwt.StandardClaims
}

```

the Roles and Business's value will be []empty

**Comment by dgrijalva** [comment]
Without more code, it's difficult to diagnose what your issue might be. My guess is the json decoder doesn't know how to decode into the `Role` and `Business` types you are using. Those types need to either be directly supported by the json package or they need to [implement the JSON `Unmarshaler` interface](https://godoc.org/encoding/json#Unmarshaler).

**Comment by dgrijalva** [comment]
Closing this ticket. Feel free to reopen if you have more information and still need help.
