### ISSUE TITLE
non-standard import "github.com/jinzhu/gorm" in standard package

### ISSUE THREAD

**Issue by Sabelo11** [dgrijalva/jwt-go#324]
I'm trying to debug a server but it give me these errors:
1) can't load package: C:\Go\src\nemaapi\server\server.go:9:2: non-standard import "github.com/gin-gonic/gin" in standard package "nemaapi/server"

2) C:\Go\src\nemaapi\server\api\accountApi.go:17:2: non-standard import "github.com/dgrijalva/jwt-go" in standard package "nemaapi/server/api"

3) C:\Go\src\nemaapi\server\db\database.go:8:2: non-standard import "github.com/jinzhu/gorm" in standard package "nemaapi/server/db

**Comment by dgrijalva** [comment]
I’m not very familiar with debugging go on windows, but that looks like the culprit is likely something about how nemaapi/server is loading dependencies. 

-dave

**Comment by dgrijalva** [comment]
Closing this as it doesn't seem to pertain to this package. Please feel free to reopen if you would like to follow up.
