### ISSUE TITLE
how to SignedString RS256 ?

### ISSUE THREAD

**Issue by thanawatkate** [dgrijalva/jwt-go#327]
key, _ := jwt.ParseRSAPublicKeyFromPEM([]byte(appkey))
	 
		token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
  
		tokenString, err := token.SignedString(key)

*** I tested and returned empty.  
Help guide me  Thank You

**Comment by dgrijalva** [comment]
Check the error. `SignedString` should never return both an empty string and a nil error. You should get one or the other. We try to make the error messages easy to understand.

The most common problem is an invalid key. You should also check the error returned `ParseRSAPublicKeyFromPEM` to make sure the parsing went ok.

**Comment by dgrijalva** [comment]
Closing issue as there's been no reply. If you still need help, feel free to reopen.

**Comment by larytet** [comment]
The following code prints an empty string. What do I miss?


		package main

		import (
			"testing"
			"time"

			"crypto/rand"
			"crypto/rsa"
			jwtgo "github.com/dgrijalva/jwt-go"
		)


		func Test_jwtSignRS(t *testing.T) {
			// https://golang.org/pkg/crypto/rsa/#GenerateKey
			privateKey, err := rsa.GenerateKey(rand.Reader, 256)
			if err != nil {
				t.Fatalf("Failed to generate a private key %v", err)
			}
			
			// publicKey := &privateKey.PublicKey
			now := time.Now()
			
			type TestClaims struct {
				HAPP string  `json:"happ"`
				jwtgo.StandardClaims
			}
			
			// Create the Claims
			testClaims := TestClaims{
				"owa",
				jwtgo.StandardClaims{
					ExpiresAt: now.Add(time.Minute).Unix(),
					NotBefore: now.Unix(),
					Issuer:    "test",
				},
			}	
			
			// https://godoc.org/github.com/dgrijalva/jwt-go#SigningMethodRSA
			token := jwtgo.NewWithClaims(jwtgo.SigningMethodRS256, testClaims)
			
			// See https://godoc.org/github.com/dgrijalva/jwt-go#Token.SigningString
			signedString, errSignedString := token.SignedString(privateKey)
			if err != nil {
				t.Fatalf("Failed to sign %v", errSignedString)
			}
			t.Logf("Signed token=%v", signedString)	
		}
