### ISSUE TITLE
Why is token expired?

### ISSUE THREAD

**Issue by tegk** [dgrijalva/jwt-go#332]
I was expecting that the token is valid but false is returned from `token.Valid`
```
token, _ := jwt.Parse(tokenString, nil)
claims, ok := token.Claims.(jwt.MapClaims)
if ok != true{
     log.Println("No claim in token")
}
if token.Valid != true{
     log.Println("token is expired")
}

```

if I parse the token like this `token.Valid `is true

```
token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		// Don't forget to validate the alg is what you expect:
		if _, ok := token.Method.(*jwt.SigningMethodECDSA); !ok {
			return nil, fmt.Errorf("Unexpected signing method: %v", token.Header["alg"])
		}
		return key, nil
	})

```

**Comment by dgrijalva** [comment]
You are ignoring the returned error. It will probably have your answer. 

Also, you are passing nil as the second argument. The token cannot be validated without a key and that function provides the key.

-dave

**Comment by vishal91** [comment]
Facing the same issue. Printed out a token. It matches with what was sent.

**Comment by tegk** [comment]
> You are ignoring the returned error. It will probably have your answer. Also, you are passing nil as the second argument. The token cannot be validated without a key and that function provides the key.
> […](#)
> -dave
> On May 24, 2019, at 8:42 AM, Till ***@***.***> wrote: I was expecting that the token is valid but false is return from token.Valid token, _ := jwt.Parse(tokenString, nil) claims, ok := token.Claims.(jwt.MapClaims) if ok != true{ log.Println("No claim in token") } if token.Valid != true{ log.Println("token is expired") } if I parse the token like this token.Valid is true token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) { // Don't forget to validate the alg is what you expect: if _, ok := token.Method.(*jwt.SigningMethodECDSA); !ok { return nil, fmt.Errorf("Unexpected signing method: %v", token.Header["alg"]) } return key, nil }) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Why would it not be possible to read a claim like expiry without providing a key?

**Comment by dgrijalva** [comment]
Claims are only interesting if the signature is valid. Without a verified signature, the claims could be modified by a malicious actor. JWT is essentially just signed JSON, so the signature is most of the point of the format.

That said, you can use the `ParseUnverified` method if you want to ignore validation and just see what's inside. I recommend against this in any context other than testing/debugging, but it's available.

**Comment by dgrijalva** [comment]
@vishal91 Did you look at the errors produced?

**Comment by tegk** [comment]
Thank you Dave for your answer which resolved my issues!
 
I am connecting a IoT device to my server and I need to look up a custom claim to look up the associated public key. This works but I was expecting that I could also prematurely check for expiry with `toekn.Valid` to give back a bad status response so I do not have to look up the public key from my database. I was expecting that `token.Valid` works because I can access the expiry time with `claims["exp"]`. I am happy to check the expiry by my self so this issue can be marked as resolved.


For reference a example:

`package main

import (
	jwt "github.com/dgrijalva/jwt-go"
	"io/ioutil"
	"log"
	"time"
	"fmt"
)

//Claims that we inlcude in the token eg a device id
type CustomClaims struct {
	*jwt.StandardClaims
	DeviceID string
}


func main() {
	//generate keys with openmssl:
	//openssl ecparam -genkey -name prime256v1 -noout -out ec_private.pem
	//openssl ec -in ec_private.pem -pubout -out ec_public.pem

	privateKeyPath := "ec_private.pem"

	//read private key from path
	keyData, err := ioutil.ReadFile(privateKeyPath)
	if err != nil {
		log.Fatal(err)
	}
	//parse the private key
	signKey, err := jwt.ParseECPrivateKeyFromPEM(keyData)
	if err != nil {
		log.Fatal(err)
	}
	// create a signer for ES256
	t := jwt.New(jwt.GetSigningMethod("ES256"))

	// set our claims
	t.Claims = &CustomClaims{
		&jwt.StandardClaims{
			ExpiresAt: time.Now().Add(time.Minute * 1).Unix(),
		},
		"DeviceID: 123",
	}
	tokenString, err := t.SignedString(signKey)
	if err != nil {
		log.Fatal(err)
	}

	token, err := jwt.Parse(tokenString, nil)
	if err != nil{
		log.Println("Problem with parsing", err)
	}



	claims, ok := token.Claims.(jwt.MapClaims)
	if ok != true{
		log.Println("Problem with claims", ok)
	}

	fmt.Println(claims["exp"])
	fmt.Println(token.Valid)

}`

**Comment by dgrijalva** [comment]
The Claims interface provides `Valid()error`. This code will be exercised again by the library after the signature is verified. It's probably still more efficient than a DB call, but only if you get a high percentage of expired tokens.

**Comment by vishal91** [comment]
Resolved for me.. Issue with SigningMethod **Type**.

**Comment by dgrijalva** [comment]
Looks like this is resolved. closing.
