### ISSUE TITLE
Getting Response & Error?

### ISSUE THREAD

**Issue by suared** [dgrijalva/jwt-go#333]
I have the below key (issued by cognito - pasted at bottom).  I validated in jwt.io successfully.

When calling: 	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) { return token }

I get both a token and an error.  The token has the right claim I can pull but I have an error that the key is not valid.  What does that mean given it is from the service and passes jwt. Can I safely ignore this error (key is of invalid type)?

	if err != nil {
		if claims, ok := token.Claims.(jwt.MapClaims); ok {
			fmt.Println(claims["iss"], claims["client_id"])
			return BasicAuth{user: claims["cognito:username"].(string)}, err  // this returns claim as expected and error
		}
		return BasicAuth{user: "nothere"}, err  // code doesn't get here
	}

key: eyJraWQiOiJOV3pPaWFxenp5enhDRmxJTDlXOFBORzQ0YXBObjBNTWJQSmcwNDVHdE5nPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiV0dWbXNXNzhiaGkwcGFQbHEzYUVtUSIsInN1YiI6ImJjMDE1N2U5LTM3YTItNDgxNi05ZTY0LTJjODg2ZDQwOGYwNyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9qUVJtU3p2SmciLCJjb2duaXRvOnVzZXJuYW1lIjoic3VhcmVkIiwiYXVkIjoiNnFwMHVtMWpwODNyYTZndm80ZGR2NjN2OGYiLCJldmVudF9pZCI6IjgxMDgwOWI1LTgyNzYtMTFlOS1hZDI1LWQ1MDkxNTk0MGZhYSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTU5MTc4MTA5LCJuaWNrbmFtZSI6IkZpcnN0VGVzdFN1YXJleiIsImV4cCI6MTU1OTE4MTcwOSwiaWF0IjoxNTU5MTc4MTA5LCJlbWFpbCI6ImRhdmlkQHN1YXJlemhvdXNlLm5ldCJ9.IAt_gJKUXPhA4G7rgDi-B9Y40mgaq9w4VJgf_vFxGh6UL6rOhAuSZ7na7jw0agmMZclqTM98tL4M1rkJvPgMajRKzdWpW3vus-o0_wzjyEQmb8qW4h1sb5HO146mW0NY6F9KuGd0yyOyySiP4hytaQhXKgIOqSsB_2rMq7BpKfnfH4u7l92uvp3iqbv_IeoeLA-RmoUfOcFxStT6gNAlO7I_5Ku0ltIQ4nPpVcnm9I3mRtuuomTSxWzNY_QFQo0q3Faw8WvUUHJcebY1VizE2c_bol52uns7PyiCHQEZnWES4OFFKbhK_Q33cjVfaWT9Kkx0wDfOBTkSrAXtKmWEPg

**Comment by suared** [comment]
If it helps, I was tracing another key (above one now expired so you need to regen to troubleshoot unfortunately) and these are the lines where it fails:
	if rsaKey, ok = key.(*rsa.PublicKey); !ok {
		return ErrInvalidKeyType
	}

It is in rsa.go:61.  My question is why does it pass in jwt.io?  It seems like a defect if passes in jwt.io and not in this code, correct?  What is the best way for you to see what I am seeing with fresh keys to enable it to be reproduced easily?  I can share my current key but I am sure it will be expired by the time you see it :-)  Please advise.

**Comment by dgrijalva** [comment]
Please don't share keys here. This token uses the signing method (`alg`) `RS256`. You must provide a key of type `*rsa.PublicKey` in order for the library to be able to verify your token.

If you print the error, you will see a message indicating as much. The library doesn't automatically parse the key for you, though there are helpers available for parsing keys from common formats. See `ParseRSAPublicKeyFromPEM` for an example.

**Comment by dgrijalva** [comment]
You absolutely should not ignore any error returned by `Parse`. If you get an error, one of two things happened:

- The token is invalid
- The token could not be parsed or validated

In either event, you should not trust the token. If you look at the returned error, it should provide an explanation for why it failed.

**Comment by suared** [comment]
Thank you for the pointer.  It is now solved for Cognito!  May I suggest in your example docs you add a placeholder comment that says "return Key here if RSA " in the parse block.  It would probably help save you from others running into the same issue.  Thanks again for the help!
Side note:  the key above is "garbage/ temp dev env" so no huge worry there.
