### ISSUE TITLE
ParseWithClaims Key Type error using a rsa.PrivateKey

### ISSUE THREAD

**Issue by Tibate** [dgrijalva/jwt-go#335]
Hello ! 
First thanks for your work. I'm a beginner with go and jwt and i'm building a REST app using your work and i'm having trouble with the "ParseWithClaims" method as it returns me a "Key of invalid type" error. I've read the othe rissues talking about this error and tried to parse the key, change the type etc... it still returns me the error even tho i'm using a RS256 Signing method and giving the parseWithClaims a rsa.PrivateKey.
The SignKey argument is a Byte array that i parse with the "ParseRSAPrivateKeyFromPEM" method. 

```
func GetRole(tokenString string) *string {
	NewKey,err1 := jwt.ParseRSAPrivateKeyFromPEM(SignKey)
	if err1 != nil {
		log.Println("ParseRSEPrivateKeyFromPEM : %v\n",err1)
	}
	token, err := jwt.ParseWithClaims(tokenString, &MyCustomClaims{}, func(token *jwt.Token) (interface{}, error) {

	return NewKey, nil
	})
	if err != nil {
		fmt.Println("error: ", err)
	}
	claims := token.Claims.(*MyCustomClaims)
	return &claims.Role
}
```
I really want to understand what's going wrong here maybe in my code or something i don't understand with your work. If you need another piece of code like the Token creation method i use i'll add it. Thanks a lot !

**Comment by dgrijalva** [comment]
Edited your message to include the whole function in code block.

The most obvious guess would be that you're passing a private key in where the public key is what you need. That key parsing function will give you an `*rsa.PrivateKey`, which is what you need to sign. But you need the public key to verify. Luckily, you can [get a public key from the private key](https://godoc.org/crypto/rsa#PrivateKey.Public).

Assuming this sample function isn't abbreviated for demo purposes, you may want to make a couple additional changes:

- You're going to need to return an error in some cases. For example, if you receive an invalid token or if you fail to parse your key for some reason.
- Parsing the key from PEM format isn't free. If your keys are pretty stable, I'd recommend doing that elsewhere and cacheing the result.
- The function should return (with an error, ideally) if the key fails to parse. Everything else is going to fail after that anyway.

**Comment by Tibate** [comment]
Thanks for the anwser !
I took the public Key from the private using the Public() method, it "works" i just get another error type now "crypto/rsa verification error" , so it might come from the way i generate my Keys in the first place.
Thanks for the tips.
