### ISSUE TITLE
I found that the token signed with rsa256 can be parsed directly on the website.

### ISSUE THREAD

**Issue by sun-wenming** [dgrijalva/jwt-go#336]
gen token code ： 
```
// GenRSA256TokenWithPriKey make token
func GenRSA256TokenWithPriKey(claims CustomClaims, privateKey *rsa.PrivateKey) (string, error) {
	tokenClaims := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
	return tokenClaims.SignedString(privateKey)
}
```
Do I need to encrypt the stored data again?

In http://jwt.calebb.net/  
![image](https://user-images.githubusercontent.com/22268505/58945984-7f899a00-87b7-11e9-84a1-01b9713779e4.png)

**Comment by dgrijalva** [comment]
JWT tokens do not encrypt their contents. The signature prevents tampering, but doesn't hide the contents. There's a sibling spec called JWE that supports an encrypted payload, but this library does not implement that spec. There's an open feature request to do so, but the changes would be larger than this whole library, so I haven't gotten to it.

There are other Go libraries available that support JWE, if that's what you need.

**Comment by dgrijalva** [comment]
Or you could, as you mentioned, encrypt the data yourself and stick it in a JWT, if that suits your end goals. I'd wager you'll get more mileage out of following the JWE spec.

**Comment by sun-wenming** [comment]
I have encrypted the data and stick it in a JWT. Then I will learn to learn JWE.
Thank you very much.
