### ISSUE TITLE
Why code as this？

### ISSUE THREAD

**Issue by hqm19** [dgrijalva/jwt-go#343]
func (t *Token) SigningString() (string, error) {
	var err error
	parts := make([]string, 2)
	for i, _ := range parts {
		var jsonValue []byte
		if i == 0 {
			if jsonValue, err = json.Marshal(t.Header); err != nil {
				return "", err
			}
		} else {
			if jsonValue, err = json.Marshal(t.Claims); err != nil {
				return "", err
			}
		}

		parts[i] = EncodeSegment(jsonValue)
	}
	return strings.Join(parts, "."), nil
}

**Comment by dgrijalva** [comment]
I don't understand the question.

**Comment by dgrijalva** [comment]
If you'd like to rephrase your question to be more specific, feel free to reopen.
