### ISSUE TITLE
Is there a way to flatten custom claims in the resulging JSON?

### ISSUE THREAD

**Issue by Sobakaa** [dgrijalva/jwt-go#351]
I have a case when some function will return me a map of claims and their values to add to the list of Claims. Unfortunately i have no way to tell upfront what those claims would be, i just know that it would be a string:string map.
I've tried doing something like this:
```
type CustomClaims map[string]interface{}
...
type AuthTokenClaim struct {
	*jwt.StandardClaims
	*CustomClaims 
}
...
m := MapClaims{}
m["key"] = "value"

claims := &AuthTokenClaim{
	StandardClaims: &jwt.StandardClaims{
		Audience:  "",
		ExpiresAt: expAt,
		Id:        fmt.Sprint(uuid.NewRandom()),
		IssuedAt:  issAt,
		Issuer:    "http://issuer.org",
		NotBefore: nbf,
		Subject:   "subj",
	},
	CustomClaims : &m,
}
```
However, the resulting JSON makes the "key":"value" pair nested, like that and i can't find a way to unmap it into a flat json:
```
  "iss": "http://issuer.org",
  "sub": "subj",
  "MapClaims": {
    "key": "value"
  }
```
Is there something i can do short of rewriting `SigningString` to hack marshalling?

I suppose i can do something like:
```
type MapClaims map[string]interface{}

func (MapClaims) Valid() error {
	log.Println("Not implemented!")
	return nil
}

m := MapClaims{}
m["aud"] = "aud"
m["exp"] = exp
uuids, err := uuid.NewRandom()
var id string = fmt.Sprint(uuids)
m["id"] = id
m["iat"] = iat
m["iss"] = "http://issuer.org"
m["nbf"] = nbf
m["sub"] = "subject"
m["typ"] = "Bearer"
token.Claims = m
```
But it looks a bit uglier that i'd like.

**Comment by dgrijalva** [comment]
Dealing with unknown keys is a bit tricky. This library depends on the standard library's `encoding/json` package, so you should be able to rely on any knowledge about its behavior. Also, `MapClaims` is already provided by the library and is an alias of `map[string]interface{}`.

I think your implementation looks just fine. You could clean it up by using a literal for your known values:

```go
var claims := jwt.MapClaims{
  "foo": "bar", // This value can be overwritten by otherClaims
}

for key, value := otherClaims {
    claims[key] = value
}

var importantClaims := map[string]interface{}
   "exp": exp,
   "iat": iat,
   ... etc ...
}

// Do these last so they can't be overwritten by otherClaims
for key, value := importantClaims {
    claims[key] = value
}

token.Claims = claims
```

One concern here would be about the `otherClaims` overwriting important values you want to control (such as `exp`).

There are a lot of valid solutions, but I don't know if any of them will look as tidy as you hope. I would advise you against being overly clever in this context. It's more important that your code is correct and easy to debug than tidy, especially where security is concerned.

**Comment by Sobakaa** [comment]
I'm very much new to Go, so i was not sure whether my solution looked like something experienced people would actually implement. 
That idea with ensuring important claims are not overwritten by incoming token values is a rather good one, thank you!
I guess that solves my issue so i'll go ahead and close this issue.
