### ISSUE TITLE
RSA 256: error in jwt.ParseRSAPublicKeyFromPEM

### ISSUE THREAD

**Issue by tarunja** [dgrijalva/jwt-go#353]
I am getting panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x586a3b]

I am getting cert value empty and it breaks in  jwt.ParseRSAPublicKeyFromPEM([]byte(cert)). I am not getting why I got error in this.

I am using below code :
```go
ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
			checkIss := token.Claims.(jwt.MapClaims).VerifyIssuer(cfg.Issuer, false)
			if !checkIss {
				return token, errors.New("invalid issuer")
			}
			fmt.Println("cfg.Issuer value ", cfg.Issuer)
			fmt.Println("cfg.RedisClient value ", cfg.RedisClient)
			cert, err := certChecker(token, cfg.Issuer, cfg.RedisClient)
			fmt.Println("certChecker cert value ", cert)
			if err != nil {
				return nil, errors.New(err.Error())
			}
			result, _ := jwt.ParseRSAPublicKeyFromPEM([]byte(cert))
			fmt.Println(" jwt.ParseRSAPublicKeyFromPEM result value ", result)
			return result, nil
		},
		SigningMethod: jwt.SigningMethodRS256
```

I got below logs:
cfg.RedisClient value  Redis<localhost:6379 db:0>
certChecker cert value
 jwt.ParseRSAPublicKeyFromPEM result value  <nil>

I am using github.com/dgrijalva/jwt-go v3.2.0+incompatible

**Comment by dgrijalva** [comment]
[Edited question formatting for readability]

**Comment by dgrijalva** [comment]
`result, _ := jwt.ParseRSAPublicKeyFromPEM([]byte(cert))`

The `_` here is an error value. The key is failing to parse and that error value will hold the reason why.
