### ISSUE TITLE
Error event on Sentry

### ISSUE THREAD

**Issue by RiceeeChang** [dgrijalva/jwt-go#354]
How to let this error "token contains an invalid number of segments", not send event to Sentry?

**Comment by xiliangMa** [comment]
I hove the same issue。
_, err := jwt.Parse(token, func(*jwt.Token) (interface{}, error) {
		return secret, nil
	})
err info： “oken contains an invalid number of segments”

**Comment by dgrijalva** [comment]
This library does not emit events to Sentry. The error being returned means the token is not well formed. Most likely a client is doing the wrong thing, or someone attempting something nefarious. How the error makes it from there to Sentry, I could only guess.
