### ISSUE TITLE
When create jwt token inside loop getting same token

### ISSUE THREAD

**Issue by isamankumara** [dgrijalva/jwt-go#356]
I am creating jwt tokens using jwt-go library. Later wrote a script to load test. I have noticed when I send the many concurrent request getting same token. To check more about this I created token inside for loop and result is same.

code as follows,
```
expirationTime := time.Now().Add(time.Duration(60) * time.Minute)

    for i := 1; i < 5; i++ {
        claims := &jwt.StandardClaims{
            ExpiresAt: expirationTime.Unix(),
            Issuer:"telescope",
        }
        _token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
        var jwtKey = []byte("secret_key")
        auth_token, _ := _token.SignedString(jwtKey)
        fmt.Println(auth_token)
    }
```

**Comment by 1995parham** [comment]
I think you are using the same claims for tokens so you must get the same token. If you want to get different tokens, you can set IssueAt field in StandardClaims. However, consider waiting 1 second to generate a new token because Unix timestamp has 1-second accuracy.

**Comment by isamankumara** [comment]
yes that's why..
