### ISSUE TITLE
Make SigningString() concurrent

### ISSUE THREAD

**Issue by agugaillard** [dgrijalva/jwt-go#364]
According to
``` go
// Generate the signing string.  This is the
// most expensive part of the whole deal.  Unless you
// need this for something special, just go straight for
// the SignedString.
func (t *Token) SigningString() (string, error) {
```
Why not making both marshal concurrent using [errgroup](https://github.com/golang/sync/blob/master/errgroup/errgroup.go)?

**Comment by jwkohnen** [comment]
This calls for a benchmark.  Goroutines are cheap, but they are not for free.

**Comment by dgrijalva** [comment]
I don't know how much value this adds for the complexity. The tasks here are expensive relative to the rest of the workflow, but likely not enough to justify this. The real cost here isn't any single call, but the aggregated cost of calling this millions of times, as you might in an auth server generating tokens. 

I'd be happy to be proven wrong by benchmarks, but I would expect this is more trouble than it's worth.

**Comment by dgrijalva** [comment]
I'm going to close this ticket. If you want to benchmark your changes and come back with a compelling case, feel free to reopen.
