### ISSUE TITLE
token.Valid is false and get claims is nil

### ISSUE THREAD

**Issue by Cristiyi** [dgrijalva/jwt-go#368]
i create token like this:
```go
tokenObj := jwt.New(jwt.SigningMethodHS256)
	claims := make(jwt.MapClaims)
	for index, val := range m {
		claims[index] = val
	}
	tokenObj.Claims = claims
	token, err = tokenObj.SignedString([]byte(key))
	fmt.Println(tokenObj)
	fmt.Println(token)
	return
```
and below is print result:
first print:  &{ 0xc0002217e0 map[alg:HS256 typ:JWT] map[exp:1612223473 iat:1576223473 user_id:10]  false}
second print:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTIyMjM0NzMsImlhdCI6MTU3NjIyMzQ3MywidXNlcl9pZCI6MTB9.UvglOILuTDv68ZmTZKW_H0CMDf7sZw8PDlNPpa3enkQ

and then i check token like this:
```go
token, _ := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			ctx.JSON(&models.Result{Code: 500, Data: nil, Msg: "token error1"})
			return nil, nil
		}
		return []byte("secret"), nil
	})
	fmt.Println("token", token)
	if !token.Valid {
		ctx.JSON(&models.Result{Code: 500, Data: nil, Msg: "token error2"})
		return
	}
	finToken, ok := token.Claims.(jwt.MapClaims)
	fmt.Println("fin", finToken)
```

token.Valid is false ant get claim is nil but tow function of token string value is same
first print:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTIyMjM0NzMsImlhdCI6MTU3NjIyMzQ3MywidXNlcl9pZCI6MTB9.UvglOILuTDv68ZmTZKW_H0CMDf7sZw8PDlNPpa3enkQ
second print:
token &{Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTIyMjM0NzMsImlhdCI6MTU3NjIyMzQ3MywidXNlcl9pZCI6MTB9.UvglOILuTDv68ZmTZKW_H0CMDf7sZw8PDlNPpa3enkQ <nil> map[] <nil>  false}

please help~

**Comment by dgrijalva** [comment]
I might guess it's because your token is signed with `key` and verified with `"secret"`, but that's just a guess. 

The second value returned by `Parse` is an error, describing why the validation failed. You should have a look at it. It's probably got your answer.

**Comment by matbhz** [comment]
@Cristiyi did you solve this problem? If so, how? Thanks!
