### ISSUE TITLE
Provide a way to parse JWT claims without validating

### ISSUE THREAD

**Issue by dschenkelman** [dgrijalva/jwt-go#37]
In some scenarios getting access to an in memory structure representing the claims can be really useful, for example to integrate with https://github.com/xeipuuv/gojsonschema.

The feature is mostly [already there](https://github.com/dgrijalva/jwt-go/blob/master/jwt.go#L110-L117), just would need to be exposed separately.

Thoughts?

**Comment by jakubknejzlik** [comment]
@dgrijalva how to do the parsing in recently released V3?

**Comment by magicalbanana** [comment]
@dgrijalva late the part but I'm curious, is there a way to parse the token and then validate it once you retrieve the key because retrieving the key means parsing the token to get the "user_id" inside the token?

**Comment by dgrijalva** [comment]
This is why the api accepts a callback function instead of just a key, so you can look it up. Just be sure you double check your signing method.

You can also use ParseUnverified and then Call the validation stuff yourself but I do not recommend this method.

-dave
