### ISSUE TITLE
panic: x509: no DEK-Info header in block

### ISSUE THREAD

**Issue by paulm17** [dgrijalva/jwt-go#371]
I'm attempting to port over PHP code that generates a JWT token.

```
    $signer = new Sha256();

    // Set path of private_key.pem. 
    $privateKeyString = new Key(
        "file:///box/" . $this->config['private_key_file'], $this->config['passphrase']
    );

    $assertion = (new Builder())
        ->setHeader('kid', $this->config['public_key_id'])
        ->setIssuer($this->config['au_client_id'])
        ->setSubject($id)
        ->set('box_sub_type', $type)
        ->setAudience($this->audience_url)
        ->setId(uniqid('ABC'))
        ->setIssuedAt(time())
        ->setExpiration(time() + $this->config['expiration'])
        ->sign($signer,  $privateKeyString)
        ->getToken();
```

Full Go code:  https://gist.github.com/paulm17/5fe17e751f1d10146441725c6e452a75

First I don't know if I have mapped out the above in line 82.  So any clarification welcome.

That said.  I keep on getting 

```
panic: x509: no DEK-Info header in block.  
```

Please advise, thanks.

**Comment by dgrijalva** [comment]
At a glance, I'd wager your panic on line 78 is the culprit. An error is being returned by the helper function trying to decode your key. Your key is probably not in the format expected by that helper.

**Comment by paulm17** [comment]
Thanks for the comment.

I'm afraid I don't exactly understand what you mean by the key not being in the correct format for the helper.

The helper being new Key and the format being []byte?

If you can provide just a bit more info, I can determine the best course of action.  Thanks!

**Comment by dgrijalva** [comment]
One of the tricky thing about working with crypto libraries is that there are a bunch of competing standards for how to encode a key. `jwt.ParseRSAPrivateKeyFromPEMWithPassword` is a helper function to help users unpack keys encoded in a common format. The error you pasted is being returned by that function. 

I have provided a few helper functions, such as this one, but decoding serialized keys is really outside the scope of this library. There are just too many formats for it to be practical. The `crypto` libraries should have all the tools you need, provided you know how your key is serialized. The goal is to get from whatever data is in your `[]byte` to an `*rsa.PrivateKey` that can be used by this library for signing.

**Comment by paulm17** [comment]
Thanks for the reply.

>  I have provided a few helper functions, such as this one, but decoding serialized keys is really outside the scope of this library.

I did initially think this was the problem.  But it's outside of my expertise to start groking the code.

Thus I'll close this for now.  If I have time in the future to resolve this, then I'll re-open or supply a PR.

Thanks.
