### ISSUE TITLE
JWT generated using signed string throws invalid signature error in jwt.io

### ISSUE THREAD

**Issue by krishnareddyrk** [dgrijalva/jwt-go#397]
Generated a Jwt using the signedString method as below. JWT is generated when I try to parse JWT using same secret in jwt.io  throws invalid signature. Does go use secret base64 encoding?

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	ss, _ := token.SignedString([]byte("mysecret"))
	fmt.Printf("%v", ss)

**Comment by mrbanzai** [comment]
No issues here with your code and a basic `jwt.MapClaims`:
```
package main

import (
	"github.com/dgrijalva/jwt-go"
	"time"
	"fmt"
)

func main() {
	claims := jwt.MapClaims{
		"nbf": time.Now().Unix(),
		"exp": time.Now().Add(5*time.Minute),
		"id": "test",
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	ss, _ := token.SignedString([]byte("mysecret"))
	fmt.Printf("%v\n", ss)
}
```
And the output:
```
~/testit$ go run main.go
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOiIyMDIwLTA0LTA3VDIyOjM4OjUwLjgyMTEyMTYwMy0wNDowMCIsImlkIjoidGVzdCIsIm5iZiI6MTU4NjMxMzIzMH0.nVjNss_I_96EFQTn7TYebyli1a3SHBKb2FN21woPXpg
```

**Comment by krishnareddyrk** [comment]
Thanks @mrbanzai for your quick response. I am trying to generate JWT which is compatible with "secret base64 encoded".  
I mean I want to enter "mysecret" as the secret and click on "secret base64 encoded" and expecting jwt.io to verify the token generated using go.

**Comment by mrbanzai** [comment]
That checkbox is to specify that the secret you've entered is base64-encoded, which "mysecret" is not; you'd have to enter "bXlzZWNyZXQ=", the base64-encoded version of "mysecret".

**Comment by krishnareddyrk** [comment]
Thanks a lot @mrbanzai It works now.
