### ISSUE TITLE
Illegal base 64 data at input byte 41

### ISSUE THREAD

**Issue by Ghvstcode** [dgrijalva/jwt-go#414]
*Description"
Good day Guy's! I am working with a JWT lib github.com/dgrijalva/jwt-go and trying to create a signed  token, but whenever I try to parse it with claims(the signed key is accurate) I  get the illegal base64 data at inputs byte 41 error! Which is strange as the string I'm passing in is base64 and I'm trying to convert it to a slice of byte!
*Steps taken to eliminate the error*
I have tried using the stdlib base64 package to encode the string but I get the same error although with a different byte size!
@dgrijalva

**Comment by Ghvstcode** [comment]
Fixed!

**Comment by jameshalsall** [comment]
what was your fix?

**Comment by timdrysdale** [comment]
When I hit this, I fixed it by trimming the whitespace off the end of the token (I was picking up a linefeed character in my websocket payload)

**Comment by Ghvstcode** [comment]
Hey! Really sorry for the late reply.
- i was signing the JWT with claims that had weird characters(;)! So i removed the characters
