### ISSUE TITLE
Draft version?

### ISSUE THREAD

**Issue by robotvert** [dgrijalva/jwt-go#48]
Hi,

Just curious about which draft version is implemented by this library.

For instance the [ruby one](https://github.com/progrium/ruby-jwt) listed on http://jwt.io clearly states it's implementing draft 6.
Putting it in the README as they do might help.

Thanks!

**Comment by dgrijalva** [comment]
Great question.  I'm currently working on an update that includes support for JWK and JWE.  I'll make sure to document draft numbers.

**Comment by dgrijalva** [comment]
TODO: verify the 3.0.0 implementation complies with the latest version of the spec and add that information to README

**Comment by dgrijalva** [comment]
resolved by 4638392845e7c0b347923a9ffc13799c80b72ce4
