### ISSUE TITLE
Panic when parsing from request

### ISSUE THREAD

**Issue by tortis** [dgrijalva/jwt-go#49]
Hi,

I noticed that the library will panic due to invalid memory address or nil pointer dereference if there is is a space in a token.

I just noticed this while playing around with PostMan Rest Client. If I send something like:

    Authorization: asdasd asd asd asd 

There is no problem, but if I send:

    Authorization: bearer asd asd asd asd 

Then the server panics. I guess this isn't a big issue really, I just thought you should be aware of it.

**Comment by dgrijalva** [comment]
Thanks.  Can you paste the panic in here?  I tested this a few different ways and was unable to get the library to panic.

My guess would be the code using `Parse` or `ParseFromRequest` isn't checking for the returned token object to be nil.  If the header string doesn't contain a valid token sequence, it will return `nil` and an `error`.

**Comment by tortis** [comment]
Ah, I had some bad logic with if statements such that the function was not returning on error. Thanks for the response, and sorry to bother you.

Best,
David
