### ISSUE TITLE
(m *SigningMethodHMAC) Sign Expecting []byte Is Not Clear

### ISSUE THREAD

**Issue by andrewaustin** [dgrijalva/jwt-go#50]
https://github.com/dgrijalva/jwt-go/blob/master/hmac.go#L70 tries to do a type assertion on interface{} to []byte but this will not work on strings. See http://play.golang.org/p/mYMjdz8vQi for a simple example.

What I do not understand is why all the examples and tests pass a ```string``` into token.SignedString() when you should really pass in ```[]byte```. 

For example https://github.com/dgrijalva/jwt-go/blob/master/example_test.go#L28 (You can see that .Sign() is directly invoked https://github.com/dgrijalva/jwt-go/blob/master/jwt.go#L60)

In general, I do not understand why you are relying on ```interface{}``` in methods instead of explicitly expecting ```[]byte```. ```(t *Token) SignedString(key interface{}``` and ```(m *SigningMethodHMAC) Sign(signingString string, key interface{})``` for two examples.

**Comment by dgrijalva** [comment]
`SigningMethodHMAC` implements the interface [`SigningMethod`](http://godoc.org/github.com/dgrijalva/jwt-go#SigningMethod).  This interface is shared by other signing methods, not all of which can use a simple `[]byte` as the key (for example, elliptical curve).  Originally, `key` was a `[]byte`, but we had to change it to support a growing list of signing methods.

That example was wrong.  I fixed it.  I also added the required type to the documentation for the HMAC `Sign` method.
