### ISSUE TITLE
JWT produced 5 segments

### ISSUE THREAD

**Issue by DisruptiveMind** [dgrijalva/jwt-go#53]
I'm unable to recreate this occurrence but I was able to produce a JWT that contained 5 segments. I've built a test for it but have hit padding issues similar to what was resolved in: commit: 679bf0f .

JWT:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOiIyMDE1LTAxLTIyVDEzOjM5OjM2Ljc1MjcyNDA0Ny0wNTowMCIsImlkIjoxLCJpc3MiOiJsb2NhbGhvc3QiLCJpdCI6ImlaY0hjZG9JdlluSnBiRXBEaElQWWc9PSJ9.DRFip65fLbqOomUT82q1cin9s2_znpbiBcnHMU2-Vcg.eyJpYXQiOiIyMDE1LTAxLTIyVDEzOjIxOjI1LjQyMTAxMzczOC0wNTowMCIsImlkIjoxLCJpc3MiOiJsb2NhbGhvc3QiLCJpdCI6IkFETG9Bc3h1VklUdlc2MmpYd2lUYnc9PSJ9.frBtab8-eul5kle2iLwF0krmG0Cor0SeGs-3EKx6TL0
```

This results in 5 segments with header and claims correctly formatted but the third segment seems to be corrupted:

```javascript
// Header
{
  "alg": "HS256",
  "typ": "JWT"
}

// Claims
{
  "iat": "2015-01-22T13:39:36.752724047-05:00",
  "id": 1,
  "iss": "localhost",
  "it": "iZcHcdoIvYnJpbEpDhIPYg=="
}
```

The crypto segment is very odd, but the second "sub-segment" in the crypto is the claims:

DRFip65fLbqOomUT82q1cin9s2_znpbiBcnHMU2-Vcg.**eyJpYXQiOiIyMDE1LTAxLTIyVDEzOjIxOjI1LjQyMTAxMzczOC0wNTowMCIsImlkIjoxLCJpc3MiOiJsb2NhbGhvc3QiLCJpdCI6IkFETG9Bc3h1VklUdlc2MmpYd2lUYnc9PSJ9**.frBtab8-eul5kle2iLwF0krmG0Cor0SeGs-3EKx6TL0

I made a hack to accept the multiple parts and just string it back together in Parse(): https://github.com/DisruptiveMind/jwt-go/blob/parse-multiple-segments/jwt_test.go#L180

The JWT seems to validate using jwt.io if that helps anything....

**Comment by dgrijalva** [comment]
The token is not well formed.  A JWT token should contain exactly two `.` characters.  That token has 4.  Was it produced by this library?

**Comment by dgrijalva** [comment]
Base64URL encoding does not include the `.` character:
`const encodeURL = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"`

**Comment by DisruptiveMind** [comment]
I agree that it is malformed, just not sure how I was able to produce this as the character set couldn't even produce the period.

It was generated from this library. I may have done something wrong in the process but it is a straight use of the functions.

Thanks for a nice library btw.

**Comment by dgrijalva** [comment]
It looks like this token may actually be an encrypted token (JWE) rather than a signed token (JWS), which this library is designed for.  I'm looking into adding support for the latter.

https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40#section-9

**Comment by dgrijalva** [comment]
Follow #51 for updates on support for encrypted tokens.

**Comment by DisruptiveMind** [comment]
I thought that at first, but it was generated through this library. I may have somehow appended two strings during an encoding process. I'll keep an eye on #51, thanks
