### ISSUE TITLE
marshalling []string claim and casting back to []string does not accept being cast as []string

### ISSUE THREAD

**Issue by dalu** [dgrijalva/jwt-go#58]
example token
```
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiNTUwODgwYjFkNjE5NGMxZDY2MDAwMDAxIiwiZXhwIjoxNDI5MjI1NDU5LCJpYXQiOjE0MjY2MzM0NTksInByb2ZpbGVfaWQiOiI1NTA4ODBiMmQ2MTk0YzFkNjYwMDAwMDIiLCJyb2xlcyI6WyJ1c2VyIl19.U-2MBZ-EH_R_fbh8qfbc6jK8iOwmq-feN9Wo8KLj0xgL7944yALwRUx4TR1gs2pZAtHNGZY3Sgriq-vS_IgESA
```

Creating token
```go
	claims := make(map[string]interface{})
	claims["account_id"] = acc.Id.Hex()
	claims["profile_id"] = profile.Id.Hex()
	claims["roles"] = acc.Roles

	t := NewToken(time.Hour*24*30, claims)

	ts, e := t.SignedString(options.HMACkey)
	if e != nil {
		http.Error(w, e.Error(), http.StatusInternalServerError)
		return
	}

func NewToken(dur time.Duration, claims map[string]interface{}) *jwt.Token {
	t := jwt.New(jwt.SigningMethodHS512)
	t.Claims = claims
	t.Claims["iat"] = time.Now().Unix()
	t.Claims["exp"] = time.Now().Add(dur).Unix()
	return t
}
```

Verfiy and get claims
```go
func ClaimsFromToken(ts string) (*Claims, error) {
	token, err := jwt.Parse(ts, func(t *jwt.Token) (interface{}, error) {
		return options.HMACkey, nil
	})
	if err != nil {
		return nil, err
	}
	if !token.Valid {
		return nil, errors.New("token invalid")
	}
	exp, ok := token.Claims["exp"].(float64)
	if !ok {
		return nil, errors.New("token time invalid")
	}
	if int64(exp) < time.Now().Unix() {
		return nil, errors.New("token expired")
	}
	account_id, ok := token.Claims["account_id"].(string)
	if !ok {
		return nil, errors.New("account_id claim invalid")
	}
	roles, ok := token.Claims["roles"].([]string)
	if !ok {
		return nil, errors.New("roles claim invalid")
	}
	return &Claims{
		AccountId: account_id,
		Roles:     roles,
	}, nil
}
```

returns "roles claim invalid" error

When I decode the token at jwt.io I see
```json
{
  "account_id": "550880b1d6194c1d66000001",
  "exp": 1429225385,
  "iat": 1426633385,
  "profile_id": "550880b2d6194c1d66000002",
  "roles": [
    "user"
  ]
}
```
So roles is indeed a []string.

Also, imho, claims should be an interface with Marshall() and Unmarshall() functions.
```go
type Claims interface {
Marshal() ([]byte, error)
Unmarshal(data []byte) error
}
```
Because with map[string]interface{} you need to cast to type, check if type is ok, and for every claim.
Otherwise you could just wrap json.Marshall() or json.Unmarshall() and could pass a struct

**Comment by dgrijalva** [comment]
I agree it's a pain.  I haven't found a simple way to handle unmarshalling like that without re-implemnting what they did with the json library.  The sticky bit is, the validator looks at certain keys (`exp`, `nbf`), so it would have to parse the JSON twice.  Once to make those keys available to the validator and a second time to unmarshal into a struct.  If you have a good solution to this, I'm all ears.

It looks like the value is `[]string`.  Have you looked to see what the type actually is?

```
dgrijalva$ pbpaste | jwt -debug -verify -
Token len: 300 bytes
Header:
map[alg:HS512 typ:JWT]
Claims:
map[roles:[user] account_id:550880b1d6194c1d66000001 exp:1.429225459e+09 iat:1.426633459e+09 profile_id:550880b2d6194c1d66000002]
Error: Couldn't parse token: No path specified
```

**Comment by dalu** [comment]
Hmm you would need to have the struct require having
Exp and|or Nbf Iat fields.
Which could be checked with the reflect package initially or just document it
and on decode ... well you'd also need the reflect package to check for the presence of the required fields in the unmarshalled struct after Unmarshal is called.

Or let the user do manual checking, because really a JWT library should be just marshalling json and base64 encoding and concating with . and signing and verifying the signature, imho (perhaps also encoding (JWE) but not neccessarily, it would probably take a different lib to do that, which would sit "on top" of jwt and is out of scope right now.)
Because according to the draft 
https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.4 
exp, nbf, iat are all optional and oauth2 or oidc use a different set of registered claims.

The type is []interface{}, so I have to build a []string from each interface{} of []interface{}. ugh.

**Comment by dalu** [comment]
This is more complicated than I thought.
Marshalling works.
But Unmarshalling panics with invalid memory address
And when I say
```go
type Token struct {
// ...
Claims *Claims
}
```
t.Claims.Marshall undefined (type *Claims has no field or method Marshall)

**Comment by dalu** [comment]
In New()
and Parse()
a ClaimSet instance would need to be passed, so the lib knows what type to unmarshall into.

```go
type ClaimSet struct {
Subject string `json:"sub,omitempty"`
Expires int64 `json:"exp,string"`
}
cs := &ClaimSet{
Subject: "tester", 
Expires: time.Now().Unix(),
}
t := jwt.New(cs,jwt.SigningMethodHS256)
ts := t.SignedString()

// later

cs := New(ClaimSet)
token, err := jwt.Parse(myToken, cs, func(token *jwt.Token) (interface{}, error) {
    return myLookupKey(token.Header["kid"])
})
fmt.Println(token.Claims)
```

**Comment by dalu** [comment]
I give up.
It's probably best to have a separate package for every ClaimSet one could expect.
oidc one package, oauth2 one package
mycustom private claimset one package and import locally
I'll put what I have at github.com/gomango/jwt
it's a mix of yours and Google's JWT, mostly yours.
