### ISSUE TITLE
Panic when passing empty or wrong method to jwt.GetSigningMethod

### ISSUE THREAD

**Issue by labkode** [dgrijalva/jwt-go#62]
What do you think about returning an error instead panicking ?

**Comment by dgrijalva** [comment]
I'm pretty sure it returns `nil`.

**Comment by labkode** [comment]
The problem was passing nil to jwt.New()
as there is no check when calling mehtod.Alg().
Do you thing I should manage the nil myself or the New() method should return an error when the signing method is nil ?

Thanks

**Comment by dgrijalva** [comment]
I'm comfortable with it the way it is.  I don't think adding an error here improves clarity or convenience.  Somewhere, you need to do a check.  Might as well just do it before.
