### ISSUE TITLE
key is invalid or of invalid type

### ISSUE THREAD

**Issue by elgs** [dgrijalva/jwt-go#65]
I got the following error:
```
key is invalid or of invalid type
```
by the following code. I'm not sure if I'm missing anything.
```go
package main

import (
	"fmt"
	"github.com/dgrijalva/jwt-go"
	"time"
)

func main() {
	tokenString, err := CreateJwtToken()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(tokenString)
}

func CreateJwtToken() (string, error) {
	token := jwt.New(jwt.SigningMethodHS256)
	token.Claims["foo"] = "bar"
	token.Claims["exp"] = time.Now().Add(time.Hour * 72).Unix()
	tokenString, err := token.SignedString("netdata.io")
	return tokenString, err
}
```

**Comment by elgs** [comment]
It looks like SignedString is receiving `[]byte`, but it declares it accepts `interface{}`.

**Comment by dgrijalva** [comment]
That interface is a bit tricky, since each signing method requires different types.  See documentation for expected types for each signing method.

**Comment by elgs** [comment]
If this is the case, it's probably a poor interface design. The interface should hide the implementation complexity from user. I think it might be better to declare each specific sighing methods separately, taking their respective types of parameters. My $.02.

**Comment by robbert229** [comment]
I just ran into this isssue myself. I agree with @elgs.

**Comment by markotikvic** [comment]
Got the same issue here. Declared the secret as const string and got the "key is invalid" error. The error is not verbose enough, since it doesn't specify why the key is invalid. I also agree that the docs shouldn't say that the method takes in {}interface, since that is not true.

**Comment by alexeyknyshev** [comment]
@markotikvic same here

**Comment by dgrijalva** [comment]
I'm open to suggestions for API improvements. It's interface{} because every signing method requires a different key type. Without generics, it's very difficult to have this type of polymorphic behavior reflected in the API. Using interface{} in these cases is idiomatic in go. Have a look at the signing method you're using for expected key type information. 

-dave

**Comment by alexeyknyshev** [comment]
I think it's ok to use `interface{}` there. But as soon as the problem seems to be quite popular it will be great to have more self explaining error message such as:

`secret must be a []byte but got string`

**Comment by dgrijalva** [comment]
I thought about that. The current error is a defined constant, which is helpful for error checking. Maybe detail is more important here.

-dave

**Comment by bk10287** [comment]
I'd agree on adding more detail.  I just ran into this issue myself, and coming to this thread was what allowed me to sort out the issue.  If the error explicitly said the secret needed to be in byte format, it would have been a quick fix.  Also, you could just type check the secret and cast it to byte if it is a string.

**Comment by dgrijalva** [comment]
An older version of this library did some clever things with types.  Some of the security concerns around JWTs illuminated that it might not be worth the risk.  I think the ideal solution would be to enable the error to contain the necessary detail while still being comparable or type-checkable.

**Comment by filipbekic01** [comment]
You need to forward []byte("your-secret-key") to SignedString() function.

**Comment by yourmoonlight** [comment]
google took me here..

**Comment by warent** [comment]
Just encountered this problem too :)

**Comment by dgrijalva** [comment]
Should we allow strings and byte slices to be used interchangeably here? Any risks with that?

-dave

**Comment by nebiros** [comment]
@dgrijalva I guess a more verbose error message should be fine, if you check for a `[]byte` type in that method you can easily send a proper error message, ¯\_(ツ)_/¯

**Comment by happilymarrieddad** [comment]
[]byte(str) worked for me. Thanks!

**Comment by r14152** [comment]
I use all cases which suggested, in every case its gave panic error with "key is invalid",
`tokenString, err := tokenData.SignedString([]byte("key Data"))`
Every case its fail

**Comment by peregrinius** [comment]
Who else is still getting this error in 2019? 😆

**Comment by Igorpollo** [comment]
4 years later...

**Comment by markotikvic** [comment]
@dgrijalva If you're still open for suggestions, maybe adding helper functions to wrap the singing key for each signing method could work. It wouldn't break existing code and the API wouldn't change.

**Comment by happilymarrieddad** [comment]
There was an extra space at the begining of my token as well. I would suggest trying to trim the string.

**Comment by mmailhos** [comment]
You can also get this error if you are trying to sign a token with a claim signing method that differs from the Signature Algorithm of the certificate you are using.
Ex: signing with `jwt.SigningMethodHS256` instead of `jwt.SigninMethodRS256` for a `*rsa.PrivateKey`.

**Comment by AGMETEOR** [comment]
> You can also get this error if you are trying to sign a token with a claim signing method that differs from the Signature Algorithm of the certificate you are using.
> Ex: signing with `jwt.SigningMethodHS256` instead of `jwt.SigninMethodRS256` for a `*rsa.PrivateKey`.

This was the issue for me. Thanks.

**Comment by ooxoo11** [comment]
> Who else is still getting this error in 2019? laughing

Still in 2020...

**Comment by whoiswentz** [comment]
I getting this error

`var jwtKey = []byte("my_secret_key")
	token := jwt.NewWithClaims(jwt.SigningMethodES256, jwt.MapClaims{
		"email": user.Email,
		"iss":   "course",
	})

	signetToken, err := token.SignedString(jwtKey)
	if err != nil {
		return "", err
	}`

**Comment by ORESoftware** [comment]
One of the worst errors I have ever seen

**Comment by davetweetlive** [comment]
> I got the following error:
> 
> ```
> key is invalid or of invalid type
> ```
> 
> by the following code. I'm not sure if I'm missing anything.
> 
> ```go
> package main
> 
> import (
>     "fmt"
>     "github.com/dgrijalva/jwt-go"
>     "time"
> )
> 
> func main() {
>     tokenString, err := CreateJwtToken()
>     if err != nil {
>         fmt.Println(err)
>     }
>     fmt.Println(tokenString)
> }
> 
> func CreateJwtToken() (string, error) {
>     token := jwt.New(jwt.SigningMethodHS256)
>     token.Claims["foo"] = "bar"
>     token.Claims["exp"] = time.Now().Add(time.Hour * 72).Unix()
>     tokenString, err := token.SignedString("netdata.io")
>     return tokenString, err
> }
> ```

Change this tokenString, err := token.SignedString("netdata.io") like to tokenString, err := token.SignedString([]byte("netdata.io"))

**Comment by yongDataScince** [comment]
`token := jwt.NewWithClaims(jwt.SigningMethodES256, &tokenClaims{
		jwt.StandardClaims {
			ExpiresAt: time.Now().Add(tockenTTL).Unix(),
			IssuedAt: time.Now().Unix(),
		},
		user.ID,
	})

	signKey := []byte("kdnjsndjnd*jdnj212md")
	
	tkn, err := token.SignedString(signKey)
	return tkn, err`

**Comment by yongDataScince** [comment]
Hello from 2021...

**Comment by rhysstubbs** [comment]
Hopefully this might help somebody else out... I stumbled into this error due to updating my projects dependencies, if it helps my integration is for Sign in with Apple. By updating, this removed the `.Materialise()` function which I was previously returning from my keyFunc. The core of the issue is indeed todo with what type you return... For my scenario I am validating a JWT using Apples supplied JWK...

```
claims := AppleJWTClaims{}

token, err := jwt.ParseWithClaims(token, &claims, func(token *jwt.Token) (interface{}, error) {
  // audience, kid etc.

  jwk, found := set.LookupKeyID(kid)   // here "jwk" will be of type RSAPublicKey

  if !found {
    // log error etc.
    return nil, err
  }
  
  var key interface{}
  
  err := jwk.Raw(&key) // key will be of type rsa.PublicKey
  
  if err != nil {
    return nil, err
  }

  return key, nil
})
```

**Comment by igormseixas** [comment]
> > You can also get this error if you are trying to sign a token with a claim signing method that differs from the Signature Algorithm of the certificate you are using.
> > Ex: signing with `jwt.SigningMethodHS256` instead of `jwt.SigninMethodRS256` for a `*rsa.PrivateKey`.
> 
> This was the issue for me. Thanks.

Thank you so much. Hahahaha tunnel vision and a tired state prevent me to see this simple thing hahaha! Uff.

**Comment by looskie** [comment]
hope you guys are enjoying this fine 3:36AM morning.

**Comment by sagafonoff** [comment]
indeed, very enjoyable 2:18am morning

**Comment by mwenku** [comment]
3 years after this issue, i'm still getting the problem

**Comment by AGMETEOR** [comment]
@mwelwankuta have you tried the solutions on this thread?

**Comment by mwenku** [comment]
> @mwelwankuta have you tried the solutions on this thread?

I'm seeing a lot of comments and not sure which one to try
here is what my code looks like.
![image](https://user-images.githubusercontent.com/64831126/148080789-cb3f30be-7dd4-40df-9dd7-30d57f760c99.png)
and my response
![image](https://user-images.githubusercontent.com/64831126/148081309-76f43d2e-0681-468e-8beb-e5ec6b979d02.png)


could you maybe please quote reply the solution

**Comment by ponomarevkonst** [comment]
> > @mwelwankuta have you tried the solutions on this thread?
> 
> I'm seeing a lot of comments and not sure which one to try here is what my code looks like. ![image](https://user-images.githubusercontent.com/64831126/148080789-cb3f30be-7dd4-40df-9dd7-30d57f760c99.png) and my response ![image](https://user-images.githubusercontent.com/64831126/148081309-76f43d2e-0681-468e-8beb-e5ec6b979d02.png)
> 
> could you maybe please quote reply the solution

Without going into details, ES256 requires public and private key pairs, whereas HS256 requires only private key. It looks like the second algorithm is more suitable for your case. You can read more about the difference between them [here](https://stackoverflow.com/a/39239395).

**Comment by mwenku** [comment]
thank you, i ended up using something else for my tokens but was more familiar with jwt.

**Comment by raahii** [comment]
Hello from 2022. FYI, this is my stupid mistake.

```golang
e.Use(middleware.JWT(middleware.JWTConfig{
    Claims:     &MyCustomClaims{},
    SigningKey: jwtSecret,
}))
```
`middleware.JWT` accept `middleware.JWTConfig` but it's ending up the same error message.
Clearly, using `middleware.JWTWithConfig` func is correct.

**Comment by zzw96** [comment]
Tip for future readers:
```
* The [HMAC signing method](https://pkg.go.dev/github.com/golang-jwt/jwt#SigningMethodHMAC) (`HS256`,`HS384`,`HS512`) expect `[]byte` values for signing and validation
* The [RSA signing method](https://pkg.go.dev/github.com/golang-jwt/jwt#SigningMethodRSA) (`RS256`,`RS384`,`RS512`) expect `*rsa.PrivateKey` for signing and `*rsa.PublicKey` for validation
* The [ECDSA signing method](https://pkg.go.dev/github.com/golang-jwt/jwt#SigningMethodECDSA) (`ES256`,`ES384`,`ES512`) expect `*ecdsa.PrivateKey` for signing and `*ecdsa.PublicKey` for validation
```
