### ISSUE TITLE
gist example won't compile -

### ISSUE THREAD

**Issue by rabarar** [dgrijalva/jwt-go#67]
I think you need to modify the type from []byte to interface{} ... on line 151
 token, err := jwt.Parse(tokenCookie.Value, func(token *jwt.Token) (interface{}, error) {...

**Comment by dgrijalva** [comment]
Hmm.... That's not my gist.  Perhaps this is a good time to turn that into an example in the code instead...  Any volunteers?  Otherwise, I'll get to it soonish.

**Comment by rabarar** [comment]
Send it to me and I'll fix it - I'm using jwt successfully in a project as we speak...

**Comment by cryptix** [comment]
Oh wow, I totally forgot about this one, Sorry...

Wish there were notifications for gist comments. I updated it but feel free to replace it with an in repo ex - might be better to let travis catch these.

**Comment by dgrijalva** [comment]
Replaced by #130
