### ISSUE TITLE
crypto/rsa: message too long for RSA public key size

### ISSUE THREAD

**Issue by WnP** [dgrijalva/jwt-go#69]
I've try to implement this [gist example](https://gist.github.com/cryptix/45c33ecf0ae54828e63b#file-asymmetric-go) but unfortunatly [this step](https://gist.github.com/cryptix/45c33ecf0ae54828e63b#file-asymmetric-go-L111) return an error:

```
crypto/rsa: message too long for RSA public key size
```

indeed I've generate rsa key pair using:

```sh
$ openssl genrsa -out my_key.rsa 256
$ openssl rsa -in my_key.rsa -pubout > my_key.rsa.pub
```

do you know how can I fix that?

**Comment by elithrar** [comment]
Tangential: Generating a 256 bit RSA key is extremely dangerous. You should
(at a minimum) be generating a 2048 bit key.

(my suggestion is to just use the HS256 algorithm for authenticating JWT's)

**Comment by WnP** [comment]
thanks @elithrar 
just in case, do you have an example howto imlement HS256 for authenticating JWT's?

**Comment by WnP** [comment]
@elithrar may [this exemple](https://github.com/slok/go-jwt-example/blob/master/server.go) is more secure? -except the bad private key choice

**Comment by elithrar** [comment]
Yes - `t := jwt.New(jwt.GetSigningMethod("RS256"))` is much better. Use a strong key of 32 bytes in length for HMAC-SHA-256 (which is what HS256 means).

**Comment by WnP** [comment]
thanks a lot for all quick answers @elithrar it totaly fix my issue
