### ISSUE TITLE
Support for other signing methods

### ISSUE THREAD

**Issue by patbaker82** [dgrijalva/jwt-go#71]
Hi there.  Thanks for the library.

Per https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-3.1 the spec supports PSS and ECDSA.  It looks like the go crypto library supports this as well.  Do you have any plans to implement this as a signing mechanism?

If not I can take a crack at the implementation

```   
   +--------------+-----------------------------------+----------------+
   | alg Param    | Digital Signature or MAC          | Implementation |
   | Value        | Algorithm                         | Requirements   |
   +--------------+-----------------------------------+----------------+
   | HS256        | HMAC using SHA-256                | Required       |
   | HS384        | HMAC using SHA-384                | Optional       |
   | HS512        | HMAC using SHA-512                | Optional       |
   | RS256        | RSASSA-PKCS-v1_5 using SHA-256    | Recommended    |
   | RS384        | RSASSA-PKCS-v1_5 using SHA-384    | Optional       |
   | RS512        | RSASSA-PKCS-v1_5 using SHA-512    | Optional       |
   | ES256        | ECDSA using P-256 and SHA-256     | Recommended+   |
   | ES384        | ECDSA using P-384 and SHA-384     | Optional       |
   | ES512        | ECDSA using P-521 and SHA-512     | Optional       |
   | PS256        | RSASSA-PSS using SHA-256 and MGF1 | Optional       |
   |              | with SHA-256                      |                |
   | PS384        | RSASSA-PSS using SHA-384 and MGF1 | Optional       |
   |              | with SHA-384                      |                |
   | PS512        | RSASSA-PSS using SHA-512 and MGF1 | Optional       |
   |              | with SHA-512                      |                |
   | none         | No digital signature or MAC       | Optional       |
   |              | performed                         |                |
   +--------------+-----------------------------------+----------------+
```

**Comment by dgrijalva** [comment]
I started working on the `ECDSA` class of signing methods, but ended up down going down a rabbit hole on key serialization and the `JWK` format.  I keep meaning to get back to it, but I've been busy.  Feel free to give it a crack if you have the time.

Also worth noting, since I've seen some branches that are just for this purpose, you can add signing methods without forking this library.  Simply call `RegisterSigningMethod` at some point before you try to use the parser.

**Comment by dgrijalva** [comment]
For a discussion on the `none` signing method, see https://github.com/dgrijalva/jwt-go/pull/34#issuecomment-58966750

**Comment by patbaker82** [comment]
@dgrijalva Hey thanks for responding.  I'm not sure if this is what you're looking for, but I added in PSS so far.  I need to add tests.

https://github.com/patbaker82/jwt-go/commit/42328dd1dc47b3ea41ea40c22fe48e9987a6ef83

**Comment by dgrijalva** [comment]
Thanks! I'll review as soon as there are passing tests.  

Why mush it into `rsa.go` vs creating a separate file?  Might be easier to follow.

**Comment by patbaker82** [comment]
@dgrijalva Sounds good.  No reason for not creating a separate file other than it was a quick edit.  I'll clean things up and see if I can tackle ECDSA.  However I might do that in a separate branch just to get in PSS (which I need :smile: )

**Comment by patbaker82** [comment]
@dgrijalva Pull request #72 has been created to support RSASSA-PSS

**Comment by patbaker82** [comment]
@dgrijalva Pull request #74 has been created to support ECDSA

**Comment by dgrijalva** [comment]
thanks!
