### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by dgrijalva** [dgrijalva/jwt-go#75]
Opening a ticket for discussion.  There are several proposed changes that will not be backwards compatible.  It makes sense to land them together so we don't have to break integration multiple times.  These are the changes I'm thinking of for 3.x:

* Dropping support for passing `[]byte` to the RSA signing methods.  Instead, use the helper methods to deserialize your keys first.  See #59 
* Support for custom types for `Claims`.  See #66 and #73 
* Potentially adding support for `json.Number`, though I haven't fully grokked that yet.  I need to re-read the json library documentation. #68 
* Potentially moving `ParseFromRequest` to a sub package and adding some options.  This is a very popular request.

Things that look like they can land in 2.x:

* Support for `ECDSA` signing methods (#74)
* Support for `RSASSA-PSS` signing methods (#72)

I'm still on the fence about supporting none out of the box, though, if we did it would look something like https://github.com/dgrijalva/jwt-go/pull/34#issuecomment-58966750

Thoughts?  Ideas?  Did I miss something?

**Comment by itsjamie** [comment]
Actually, if we're going to land a bunch of changes, I'll take another stab at #73 over the weekend.

I've got an idea about getting rid of the map altogether for claims.

So, because the JSON Web token RFC claims have a few standardized fields: https://tools.ietf.org/html/rfc7519#section-4.1

Thoughts on making the default Claims object have at least those?

Then, the interface could be 
```go
type Claimer interface {
  Valid() error
}
```

Implementation in the package could cover the reserved claims.
```go
type Claims struct {
    Audience  string `json:"aud,omitempty"`
    ExpiresAt    int64  `json:"exp,omitempty"`
    Id        string `json:"jti,omitempty"`
    IssuedAt  int64  `json:"iat,omitempty"`
    Issuer    string `json:"iss,omitempty"`
    NotBefore int64  `json:"nbf,omitempty"`
    Subject   string `json:"sub,omitempty"`
}
```

```go
func (c *Claims) Valid() error {
  //impl that checks against nbf, iat, exp. 
  //Claims that have well defined behaviour, and don't need external information to validate them.
}

func (c *Claims) VerifyIssuer(iss string) error {
  //Helper to validate issuer from claims object yourself
}
...
```

Then in a separate package I believe you can do..
```go
type Claims struct {
  jwt.Claims
  Scope CustomType ```json:"scope"```
  // could add private data used for validation when parsing the token
  validIss string
}

func (c *Claims) Valid() error { 
  c.Claims.Valid()
  c.Claims.VerifyIssuer(c.validIss)
  // Additional validation in my extended claims!
}
```

**Comment by dgrijalva** [comment]
Does that work?

-dave

**Comment by itsjamie** [comment]
I think it will from what I've read.. I'll test it tonight though.

**Comment by itsjamie** [comment]
Yep.
http://play.golang.org/p/OwqvFI6wB3 :+1:

**Comment by dgrijalva** [comment]
Trying to wrap my simple brain around this.  Is this what you're doing here? http://play.golang.org/p/r9uGvexzJR

**Comment by dgrijalva** [comment]
That's super rad!  I didn't realize that would work.  It might still be prudent to leave the map approach as an option.  There are probably use cases where you just want to capture everything.  Plus, we have to use an interface anyway.  Might as well.

**Comment by itsjamie** [comment]
> Trying to wrap my simple brain around this. Is this what you're doing here? http://play.golang.org/p/r9uGvexzJR

Sounds like a plan regarding leaving in MapClaim as an option, I'll update the pull request tomorrow.

**Comment by StephanDollberg** [comment]
Any time frame on when you plan to release 3.0?

**Comment by itsjamie** [comment]
The changes to the Claims object are going in #73. I think it's ready to merge, after that I'll move onto other issues to get the library to a stable 3.0.

We're using it pretty heavily in our own API.

**Comment by dgrijalva** [comment]
There are quite a few users of this library, so I'd like to give people an opportunity to review/comment before it's released, but there should be a branch available this week to start playing with new features/changes.

**Comment by dgrijalva** [comment]
Is this a good opportunity to move `ParseFromRequest` into a sub-package and provide some more options there?

**Comment by axdg** [comment]
+1 for moving `ParseFromRequest` into a sub-package. What new features were you thinking of? It would be great to be able to pass in a method other than `BEARER` for the auth header.

**Comment by elithrar** [comment]
Suggestion: drop the use of `key interface{}` in the following functions. Accept the concrete type - e.g. `rsa.PrivateKey`.
```go
func (m *SigningMethodECDSA) Sign(signingString string, key interface{}) (string, error)
func (m *SigningMethodECDSA) Verify(signingString, signature string, key interface{}) error
func (m *SigningMethodHMAC) Sign(signingString string, key interface{}) (string, error)
func (m *SigningMethodHMAC) Verify(signingString, signature string, key interface{}) error
func (m *SigningMethodRSA) Sign(signingString string, key interface{}) (string, error)
func (m *SigningMethodRSA) Verify(signingString, signature string, key interface{}) error
func (m *SigningMethodRSAPSS) Sign(signingString string, key interface{}) (string, error)
func (m *SigningMethodRSAPSS) Verify(signingString, signature string, key interface{}) error
```
(If I've missed the rationale behind the use of interface{} here in the first place, let me know)

**Comment by dgrijalva** [comment]
All the methods comply with the interface `SigningMethod`, which is why they're all the same.

**Comment by dgrijalva** [comment]
Typically, the user of this library does not call those methods directly.  Instead, you'd use `Parse` or `Token.SignedString` to validate or sign a token, respectively.  Having non-uniform method signatures doesn't get you very far and requires much more reflection gymnastics of `Token`.

**Comment by EricLagergren** [comment]
Hi, just thought I'd like to bring up the "leeway" part of nbf: https://tools.ietf.org/html/rfc7519#section-4.1.5

It could simply be a exported int that the user could set to allow for some leeway. I could submit a PR if you'd like.

**Comment by EricLagergren** [comment]
Also, the `RegisterSigningMethod` and `GetSigningMethod` functions are both not thread safe. It'd be trivial to make them thread-safe, as well as throw fatal errors if you duplicate a name.

**Comment by EricLagergren** [comment]
Also, not to be the guy who barges in and asks a ton of questions, but I'm curious about this: https://github.com/dgrijalva/jwt-go/commit/fe9a138186b62b048aadf0c2aa411b90705885fc#commitcomment-13251427

**Comment by dgrijalva** [comment]
@EricLagergren I'm inclined to leave the signing method factory stuff the way it is for now.  It's a little bit inelegant, but it's pretty far outside of the common usage of the library and a bit more flexible this way.  If you'd like to re-open discussion on this, feel free to open a separate ticket for better visibility.

**Comment by dgrijalva** [comment]
Closing this ticket.  Everything in here is either complete or captured in the 3.0.0 milestone.
