### ISSUE TITLE
Couldn't parse token: signature is invalid

### ISSUE THREAD

**Issue by tanookiben** [dgrijalva/jwt-go#81]
The example on jwt.io has the following example:

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ` encoded with `secret`

In `jwt-go/cmd/jwt`, I created a file named `key` with content `secret` and ran the following command but encountered an error:

```zsh
» echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ | go run app.go -key="./key" -verify -
Error: Couldn't parse token: signature is invalid
exit status 1
```

Any ideas on what I'm doing wrong?

**Comment by dgrijalva** [comment]
Works for me.  Do you perhaps have a trailing newline in your key file?

```
$ echo -n secret > key
$ echo "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ" | jwt -key key -verify -
{
    "admin": true,
    "name": "John Doe",
    "sub": "1234567890"
}
```

**Comment by tanookiben** [comment]
:facepalm: darn it. Thanks for the tip!
