### ISSUE TITLE
Cannot Valid parse

### ISSUE THREAD

**Issue by tommoholmes10** [dgrijalva/jwt-go#82]
I have code like this
```go
token := jwt.New(jwt.GetSigningMethod("HS256"))
	token.Claims["ID"] = "Christopher"
	token.Claims["exp"] = time.Now().Add(time.Hour * 1).Unix()
	s, e := token.SignedString([]byte("unicornsAreAwesome"))

	if e != nil {
		panic(e.Error())
	}
	fmt.Println(s)
```
when I'm running I get
``
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IkNocmlzdG9waGVyIiwiZXhwIjoxNDM5ODE2Njg2fQ.OU2K92mLwEy9hrL-gwiNEm1Rd_vVVCZ0o3mYxdT2e-I
``
but when I want to parse it with this code
```go
myToken := "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9leGFtcGxlLm9yZyIsImF1ZCI6Imh0dHA6XC9cL2V4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.KcNaeDRMPwkRHDHsuIh1L2B01VApiu3aTOkWplFjoYI"
	token, err := jwt.Parse(myToken, nil)

	if err == nil && token.Valid {
		fmt.Println("Your token is valid.  I like your style.")
	} else {
		fmt.Println("This token is terrible!  I cannot accept this.")
	}
```
I have ``This token is terrible!  I cannot accept this.``

**Comment by dgrijalva** [comment]
Passing `nil` as the second argument to `Parse` makes it impossible to validate the token.  Here are your options:

1) Pass a function to allow it to validate the signature of the token:
`token, err := jwt.Parse(myToken, func(t *jwt.Token)interface{}{ return []byte("unicornsAreAwesome")})`

2) If you don't care about validation, you can ignore err:
`if token, _ := jwt.Parse(myToken, nil); token != nil {`

The former is usually better than the latter as the whole point of these tokens is to verify them before you use them, but you may have different constraints.

**Comment by dgrijalva** [comment]
You can always print out the error to see why it failed.  For example the code you provided will probably print out "no Keyfunc was provided."

**Comment by dgrijalva** [comment]
Closing.  Feel free to reopen if you have further questions.

**Comment by tommoholmes10** [comment]
when I run this code
```go
	myToken := "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9leGFtcGxlLm9yZyIsImF1ZCI6Imh0dHA6XC9cL2V4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.KcNaeDRMPwkRHDHsuIh1L2B01VApiu3aTOkWplFjoYI"
	token, err := jwt.Parse(myToken, func(token *jwt.Token) (interface{}, error) {
		return []byte("unicornsAreAwesome"), nil
	})
	if err == nil && token.Valid {
		fmt.Println("Your token is valid.  I like your style.")
	} else {
		fmt.Println("This token is terrible!  I cannot accept this.")
	}
```
I get still same ``This token is terrible! I cannot accept this.``

**Comment by tommoholmes10** [comment]
okee thanks
