### ISSUE TITLE
3.0 - Claims panic

### ISSUE THREAD

**Issue by orangesoup** [dgrijalva/jwt-go#89]
Hey!

I'm trying out the 3.0.0 release, works perfectly fine except one thing, I can't read the claims.
`Panic: jwt.Claims is *jwt.StandardClaims, not jwt.StandardClaims`

Code is pretty much the same as it is in the readme.
```go
token, err := jwt.ParseWithClaims(t, keyFunc, &jwt.StandardClaims{})
claims := token.Claims.(jwt.StandardClaims)
fmt.Println(claims.Subject)
```

Any idea how to fix it? Or should I just go back to 2.0 for the time being?

**Comment by elithrar** [comment]
`claims := token.Claims.(jwt.StandardClaims)` should be `claims :=
token.Claims.(*jwt.StandardClaims)` - note the asterisk denoting a
pointer during the type assertion. You can guard against panics like
this by using the `claims, ok := token.Claims(someType)` idiom as per
https://golang.org/ref/spec#Type_assertions

**Comment by orangesoup** [comment]
Bah, thanks. Need to update the readme though!
