### ISSUE TITLE
Usage with Google Sign-In for Websites

### ISSUE THREAD

**Issue by pbberlin** [dgrijalva/jwt-go#92]
I implemented Googles Oauth2 for websites.
      https://developers.google.com/identity/sign-in/web/backend-auth

ParseRSAPublicKeyFromPEM() seems to expect a **full** PEM encoded public key,
such as one of these: https://www.googleapis.com/oauth2/v1/certs

But the JavaScript creates a PWT with only the key  **to** the PEM above, i.e.
      9015759ea37707cb6d325cca00e6299231b7f72f

The PWT is created by https://apis.google.com/js/platform.js.

How is that supposed to work?
Is there a "PEM Key Lookup" stage, that I overlooked?
Is my use case off base?

I changed the code.
I replaced the *key* with the full PEM.
Then it works perfectly.

Regards
  Peter

**Comment by dgrijalva** [comment]
That function is just a helper.  The RSXXX signing methods expect an `rsa.PublicKey` for validating and an `rsa.PrivateKey` for verification.  You can get those any way you see fit.

**Comment by dgrijalva** [comment]
Closing this ticket as it's inactive.  If you would like more help with this, feel free to reopen the ticket or message me.
