### ISSUE TITLE
Incorrect comments for SignningMethodRSAPSS.Verify() / Sign()

### ISSUE THREAD

**Issue by northbright** [dgrijalva/jwt-go#95]
Hi Dave,  

I found 2 incorrect comments in `rsa_pss.go`(line 72 and 101):

// Implements the Verify method from SigningMethod
// For this verify method, key must be an **rsa.PrivateKey(should be *rsa.PublicKey?)** struct
func (m *SigningMethodRSAPSS) Verify(signingString, signature string, key interface{}) error {

// Implements the Sign method from SigningMethod
// For this signing method, key must be an **rsa.PublicKey(should be *rsa.PrivateKey?)** struct
func (m *SigningMethodRSAPSS) Sign(signingString string, key interface{}) (string, error) {

#### PS:
Your **jwt-go** is cool and I love it:)

**Comment by dgrijalva** [comment]
thanks!
